### ISSUE TITLE
Repository release

### ISSUE THREAD

**Issue by Kangodo** [BSData/catalogue-development#1]
Let's start of in our new home with the first question(s)!

How exactly do we handle releases to the public?
Can anyone do it? Can I release, or is that an admin-only thing?
Whenever we want? Once every week (or two)? After a certain number of commits?

My idea would be to release every Sunday-evening if there are enough commits/changes.

I'm curious because I've added 9 units to a catalogue and changed another 10.
People are aching for those updates ;)

**Comment by amis92** [comment]
Closed because of age
