### ISSUE TITLE
Original Contributor gone, would like to continue his work

### ISSUE THREAD

**Issue by Trommelbohne** [BSData/catalogue-development#10]
Hi, I am somewhat new to Github so please bear with me if I say something stupid.

I started updating the data files for "Galeforce 9s - Tanks" and would like to commit the changes to the "official" repo. So I put in a pull-request, but as far as I can see, the last activity in there has been in July of last year.

What would be my logical next step to make my additions available to the community? Is it sensible to replace the Repo entirely? 

Any help / explanation of how to proceed in a case like this would be much appreciated. :)

Thanks in advance
Cheers Nicolas

**Comment by amis92** [comment]
It certainly seems like you did a pull request, but 6 days of inactivity doesn't mean the original author is gone :D

As this is a repo-specific issue, it belongs to that repo. It seems you could simply join the team, so why not open Join Request as per https://github.com/BSData/bsdata/wiki
