### ISSUE TITLE
Non-released repositories

### ISSUE THREAD

**Issue by amis92** [BSData/catalogue-development#100]
There are repositories that are neither archived nor released, and weren't updated since at least 2 years:

Repository | Last update
-|-
https://github.com/BSData/dragon-rampant | 2016-07-29
https://github.com/BSData/malifaux | 2016-09-22
https://github.com/BSData/RoguePlanet | 2014-11-10
https://github.com/BSData/spectre-operations | 2016-12-01
https://github.com/BSData/volkskrieg | 2018-05-18

They should probably be archived.

**Comment by Mad-Spy** [comment]
These have all been archived.
