### ISSUE TITLE
New repo: Heavy Gear Blitz

### ISSUE THREAD

**Issue by coldgap** [BSData/catalogue-development#101]
Hello! I've written a set of data files for Dream Pod 9's Heavy Gear Blitz! They are located at https://github.com/coldgap/Heavy-Gear-Blitz-LRB. Most of the files are ready for 1.0 release (though some are not quite ready for prime-time). What should I do to get the right ones available in Battlescribe?

**Comment by coldgap** [comment]
Any update?

**Comment by Mad-Spy** [comment]
.preview

**Comment by Mad-Spy** [comment]
.approve
