### ISSUE TITLE
Abysse jeux

### ISSUE THREAD

**Issue by Pralist** [BSData/catalogue-development#102]

**Comment by Pralist** [comment]
Bonjour j'aimerais creer un datafile pour un jeu que j ai creer mais je ne trouve pas comment faire merci de me repondre si vous avez la solution

**Comment by amis92** [comment]
Hello - please use English language for communication.

**Comment by Mad-Spy** [comment]
The best way to learn how to create data files is to open existing ones in the Data Editor and see how they have been done. Also, join the Data Author Discord (linked below) to get more help.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Once you've created your data files, raise a new issue here to get a BSData repo created.
