### ISSUE TITLE
New repo: Warcaster: Neo-Mechanika

### ISSUE THREAD

**Issue by DarthFraggle** [BSData/catalogue-development#107]
Hello, I've got files prepped for Warcaster.

**Comment by DarthFraggle** [comment]
.approve

**Comment by DarthFraggle** [comment]
@amis92  It looks like someone else requested a spot for this game system a couple days before I did. What do you normally do in situations like this? I think my files may be more complete ( including all special rules and options).

**Comment by DarthFraggle** [comment]
[](https://github.com/DarthFraggle/warcaster-neo-mechanika)

Repository created using template.

**Comment by DarthFraggle** [comment]
.approve

**Comment by SabreDeC** [comment]
Yeah his is much better. I literally just taught myself this stuff (the data editor and github in general) for the first time in like....an evening so I don't know what I'm doing. By all means disregard my repo request, as this guy knows what he's doing lol

**Comment by DarthFraggle** [comment]
Thanks @SabreDeC. Yours looked much better than my first attempt.

**Comment by Mad-Spy** [comment]
.approve

**Comment by Mad-Spy** [comment]
Please upload your files to the new repository as soon as possible. 
Empty repositories will be deleted after 1 month.

**Comment by SabreDeC** [comment]
I have been receiving the updates for this repo. Please make sure that the file upload reminder has been forwarded to the actual contributor. I am not the one writing this repo.
