### ISSUE TITLE
Kill Team Specialists

### ISSUE THREAD

**Issue by foolsama** [BSData/catalogue-development#11]
It looks like a big project, but for Kill Team Detachments it would make more sense (to me) to make the Entry link on a per-model basis rather than per squad. This way you can define which model is which specialist.  Also recommend adding the 'Leader' specialist.

**Comment by alphalas** [comment]
While that sounds like a great idea in theory, you're assuming that each and every squad that can be in used in kill team is built on a per model basis. Many squads are built on a unit basis or you simply select the number of models and any extra wargear in the squad, as opposed to individual models. For squads built in such away making the specialist on a per model basis would not work without a complete rewrite of said squads.
