### ISSUE TITLE
New repo: In Her Majestys Name

### ISSUE THREAD

**Issue by TCQN-8** [BSData/catalogue-development#110]
Finding myself with more time on my hands I have been working on data files for 'In Her Majesty's Name. I was also encouraged to do this as I read that the 2nd edition might launch in the next year or so.
I have put in all the options from the core game but neither of the expansions. I haven't managed to do all the catalogues for the various companies, only the six companies I actually own. I will look at including the rest of the companies from the core rules in the near future. Then perhaps the additional stuff from the two expansions. However, I can't see myself being able to include all the new companies form the expansions since there are so many of them!
I have no experience of using Github, or much programming experience in general. I'm wondering if anyone  can help with this? I have attached this files for perusal if required.
[InHerMajestysName.zip](https://github.com/BSData/catalogue-development/files/4433598/InHerMajestysName.zip)

**Comment by TCQN-8** [comment]
Now have the files in TCQN-8/bsdata. Not sure that this was the correct thing to do? Two more companies also added.

**Comment by Mad-Spy** [comment]
@TCQN-8 you'll need to re-upload your files as the unzipped versions when you add them to the BSData repo.

**Comment by Mad-Spy** [comment]
.approve

**Comment by TCQN-8** [comment]
@Mad-Spy I have re-loaded the files to TCQN-8/BSData. Is this the right place to put them? I have now added the missing core companies and, since talking to you on github (about two weeks ago), rewritten the game system file and modified all the catalogue files!

**Comment by TCQN-8** [comment]
Sorry, didn't mean to close this until things are confirmed as being OK!

**Comment by Mad-Spy** [comment]
Please upload your datafiles to the new repo as soon as you can.
