### ISSUE TITLE
New repo: wh40k SECOND EDITION

### ISSUE THREAD

**Issue by fyodo125** [BSData/catalogue-development#111]
I would like to create a standard template for warhammer 40,000 - second edition (~1993). 
I'm with a growing group of currently over 1,400 people from all over the world who like, play, collect warhammer 40k stuffs from that era and many of them keep asking us whether there's a file for use with battlescribe. I'd like to get the basic structure for that edition of 40k going but I need HELP.

What does this version of 40k need?
- three base categories of units (characters, troops, support)
- balancing through percentages to total points: e.g. no more than 50% of total points value can consist of <characters>, at least 25% of total points value must be <troops> etc. 
- no detachments or formations
- nice to have-feature: Allies. Each army can add allies from certain other factions to their support pool

WARGEAR - probably the most complicated feature?
- slots for wargear (some characters may take 1 additional wargear item and pay points for them, others may take up to 3 wargear items from and so on)
- faction-based wargear. Same as above, but accessible only by certain factinos
- vehicles can take special wargear, only available for vehicles (general vehicle wargear and faction-specific vehicle wargear) 

Profiles
- if possible, special profiles for vehicles, with relatively LOADS of information about armour values, speed values and damage tables. 

Where do I start and how do I implement these things?

**Comment by fyodo125** [comment]
.approve

**Comment by fyodo125** [comment]
approve

**Comment by fyodo125** [comment]
approve

**Comment by fyodo125** [comment]
I have kind of tried my best to create a .gst and ran the data indexer and used a public dropbox folder to store everything - which is actually just a gst and index file atm. I am not sure how or to tell battlescribe about the points ratios and how to add catalogues. I tried adding a new catalogue link in the data editor, but nothing appeared. I'm assuming catalogues are the "folders" or army books in which I define single units and add their profiles, according to the (unit) categories I defined in the main catalogue.

**Comment by fyodo125** [comment]
I've been working with this: https://github.com/BSData/catalogue-development/wiki/Data-Admin-Guide
I don't quite understand some of the instructions but I have tried my best and put everything in a public dropbox folder and created a repository with the github desktop application too. I've also modified the readme as instructed as well as I could. I am not sure where the name/adress and links have to go. Tried editing some files with the github app, but could not change anything.

I noticed the other template files still include placeholder template names and titles. Not sure how to upload this anywhere? I'm pretty clueless in general, not sure about the instructions given.

I find I'm actually struggling to follow the tutorial, unfortunately. Help and/or advice would be much appreciated. Is there any guide on how to set up new data files? I mean, like, how to tell battlescribe which is which, rather than uploading to and working with github.

**Comment by fyodo125** [comment]
The desktop github app did not upload all the files, so I've uploaded them manually through the site:
https://github.com/fyodo125/wh40ke2/upload

Need help with this. 
I don't actually think that github is exactly needed for this project, but I need help with the gst file (see above). Anyway, these are the files so far, as best as I could create them according to the tutorials.

**Comment by Mad-Spy** [comment]
Joining the Data Authors Discord, and looking at existing files is the best way to learn how to create data files for Battlescribe.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Once you've created your data files, open a new issue here to request that a repository be added.
