### ISSUE TITLE
New repo: Behind Omaha

### ISSUE THREAD

**Issue by EryelShest** [BSData/catalogue-development#118]
Behind Omaha is a german community built WW2-tabletop using 1/72 models featuring several nations and their wargear, tanks and guns.

The homepage is www.behind-omaha.de.

**Comment by EryelShest** [comment]
Moin!

I'd like to ask if you'd like to create the repo.

Sincerely
Eryel

**Comment by amis92** [comment]
Hi @EryelShest ,

I'm not sure I understood your request. Are you requesting for the repository to be created so that you can upload your files to it, or are you asking us to create datafiles for this system?

**Comment by EryelShest** [comment]
Moin @amis92!

I'm sorry for the confusion. I got the files ready for upload, so I only need the repository to be created.

Sincerely
Eryel

**Comment by Mad-Spy** [comment]
If possible, please provide a link to the existing files in their current Github repo.

**Comment by EryelShest** [comment]
The files are located here:
https://github.com/EryelShest/Behind-Omaha-Files

More factions will be added as soon as they're ready.

**Comment by Mad-Spy** [comment]
You will need to re-save your files as the unzipped versions and then re-upload them to your repo.

**Comment by EryelShest** [comment]
Done

**Comment by Mad-Spy** [comment]
.approve

**Comment by Mad-Spy** [comment]
Please upload your files to the new repo as soon as possible. Empty repositories will be deleted after 1 month.
