### ISSUE TITLE
Aeronautica Imperialis not appearing in datafile list

### ISSUE THREAD

**Issue by surfimp** [BSData/catalogue-development#119]
The data files for Aeronautica Imperialis were (AFAIK) added to BSData at some point, but they are no longer appearing in the list.

Here is the repo:
https://github.com/BSData/aeronautica-imperialis

Would it be possible to have these re-added to the available datafiles list?

**Comment by amis92** [comment]
Reason: https://github.com/BSData/bsdata/issues/208
