### ISSUE TITLE
No longer have push access

### ISSUE THREAD

**Issue by Itsacon** [BSData/catalogue-development#12]
I just started work on adding the IA datasheets to the new w40k repository, but I don't have push access anymore (probably because of the rename stuff).

Can I get permission again?

**Comment by amis92** [comment]
1. You should probably coordinate that effort over on [Gitter](https://gitter.im/BSData/wh40k) as there already is work being planned/done.
2. It's not a mistake, most people have lost push access. See explanation over on https://github.com/BSData/bsdata/wiki#getting-started (bullet 3)

Please ask, if I can help you with anything else.
