### ISSUE TITLE
New repo: relicblade

### ISSUE THREAD

**Issue by Drizzt-IT** [BSData/catalogue-development#120]
Hello, 
I'd like to maintain the repo for the relicblade repo.

This is the Game: https://relicblade.com

Kind regards,
Konrad

**Comment by Mad-Spy** [comment]
Have you already created the data files for this game?

**Comment by Drizzt-IT** [comment]
Yes in parts,
I am currently in contact with the game designer. I would like to include a lot of rules and would like to have his consent.
But the structure is done.

**Comment by Mad-Spy** [comment]
Do you have a repository on Github already you can provide a link to?

**Comment by Drizzt-IT** [comment]
Nope having all locally at the moment.

**Comment by Mad-Spy** [comment]
OK, please create a personal repo using the BSData template and upload your data files to it. Make sure to upload unzipped versions (save as .cat and .gst).

**Comment by Drizzt-IT** [comment]
Why doing double the effort?

**Comment by Mad-Spy** [comment]
The files need to be unzipped or the process which makes them available on Appspot won't work.

**Comment by Drizzt-IT** [comment]
ok, done the link to the repo is:
https://github.com/Drizzt-IT/relicblade
IS there anything else to do?

**Comment by Mad-Spy** [comment]
Please upload your game files to the BSData repo as soon as possible. Repositories which are unused will be deleted after 1 month.

If you haven't already joined the Data Authors Discord, I suggest doing so.

**Comment by Drizzt-IT** [comment]
Ok, thx

**Comment by Drizzt-IT** [comment]
@Mad-Spy I guess I can now delete my personal repo correct?

**Comment by amis92** [comment]
I mean, you can - but it seems you haven't uploaded anything to the new repo?

**Comment by Drizzt-IT** [comment]
Yes, I didn't upload anything till now.
I first wanted to have the repo setup stuff ready before I upload the content.

**Comment by amis92** [comment]
Cool. Then, as per https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide all that's left is to release your work to the wide world :)
