### ISSUE TITLE
New repo: Confrontation 3.5

### ISSUE THREAD

**Issue by zombied00d** [BSData/catalogue-development#122]
In a fit of nonsensical optimism I apparently have decided to enter the rules for Confrontation and all of the units in it by hand. Because I am dumb.

**Comment by Mad-Spy** [comment]
Have you already created the data files? If not, please create your datafiles first. You can create a personal repo using the BSData template to ensure that the necessary "system" files are in place.

**Comment by Mad-Spy** [comment]
Closing due to lack of response.
