### ISSUE TITLE
New repo: Warhammer 40 000 french translation

### ISSUE THREAD

**Issue by shobu13** [BSData/catalogue-development#123]
name: warhammer 40 000 fr

french translation of warhammer 40k rules, based on
https://github.com/BSData/wh40k
link: https://github.com/shobu13/warhammer-40000-8th-edition-fr

Work in Progress

currently working on: drukhari

**Comment by amis92** [comment]
@shobu13 please see https://github.com/BSData/catalogue-development/issues/15

We're not adding translated repositories currently. It's non-maintainable because we constantly update our datafiles.
