### ISSUE TITLE
Bug in AoS nurgle army

### ISSUE THREAD

**Issue by Excidium666** [BSData/catalogue-development#126]
I have found 2 bugs in age of sigmar nurgle. First -  in nurgle units list should be 2 units of skaven: Plague monks, Plague censers bearers
Second-  Batalion need unit with great unclean one keyword. Rorigus have that keyword

**Comment by Excidium666** [comment]
Big with chosing hosi is fixed but i found next one. 

First - in nurgle units list should be 2 units of skaven: Plague monks, Plague censers bearers

**Comment by Mad-Spy** [comment]
Please report issues with particular data sets on the relevant page for that data set, in this case https://github.com/BSData/warhammer-age-of-sigmar/issues
