### ISSUE TITLE
New Repo: Spectre Operations v2

### ISSUE THREAD

**Issue by Tattoosavage** [BSData/catalogue-development#127]
I would like to add this game to the bsdata files repository.

https://github.com/Tattoosavage/Spectre-Operations-v2

**Comment by amis92** [comment]
Hi. There's already a `spectre-operations` repository in BSData. I'll invite you as a collaborator there.

However, please read carefully https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide - including **Most Common Mistakes** section - but all others as well.

**Comment by amis92** [comment]
@Tattoosavage you've now been invited.

Repository: https://github.com/BSData/spectre-operations

Invitation can be accepted at: https://github.com/BSData/spectre-operations/invitations

**Comment by Tattoosavage** [comment]
Hiya

No thankyou. That old one is out of date, only has a few items in it, and
is no longer supported.
The one I've made is the one the community is currently waiting on
(including the older original author), and is for V2 and is complete,
and my responsibility alone.
We are wanting to start afresh please.

Yours
Mark.
