### ISSUE TITLE
New repo:

### ISSUE THREAD

**Issue by english-boar** [BSData/catalogue-development#129]
Hello!

I was wondering how I would go about getting a new database sorted for a game that isn't currently supported by the name of Burrows and Badgers.

Thanks in advance for any help

**Comment by amis92** [comment]
There has been already a request here: https://github.com/BSData/catalogue-development/issues/97

If you're interested in trying to do these datafiles yourself, please visit `#new-data-developers` on our Discord. Link is on the homepage: https://github.com/BSData
