### ISSUE TITLE
Managing Force Entries

### ISSUE THREAD

**Issue by Dr-Csernus** [BSData/catalogue-development#13]
Hello. I am working on the War of the Ring repository, where you can take two types of Forces (Army and Allies, with allies limited to 25% of the total points).

There is however a catalogue (The Forgotten Kingdoms) which can only be taken as Allies. Do I have an option to limit this catalog to be taken only as Allies?

p.s. I posted this here as I think it's not just WotR-related, the answer can be useful in any other systems.

**Comment by capitaladot** [comment]
Hey there. The Horus Heresy has the same situation with Daemons, but I don't believe BS has the ability to "jail" a particular CAT to a particular Force. It would be a great feature add!

**Comment by amis92** [comment]
Since v2.0 (or 2.01) we can add Force Types in Catalogues.

**Comment by DrTobogganMD** [comment]
No solution to merge catalogues exists.
