### ISSUE TITLE
New repo:Limbo Eternal War

### ISSUE THREAD

**Issue by OfficerBrush** [BSData/catalogue-development#132]
https://github.com/OfficerBrush/Limbo-Eternal-War

**Comment by OfficerBrush** [comment]
Is there something I need to do for you in order to have the new Repo? I have separate files if you need them. I planned on putting them in once it was up.

**Comment by amis92** [comment]
@OfficerBrush we've just had some scripting hiccups, nothing yet to do for you 👍

**Comment by Mad-Spy** [comment]
This repo is now ready for use. Your upload should use the unzipped .cat files in order for the BSData release workflow to work correctly.
