### ISSUE TITLE
New repo:Team Yankee

### ISSUE THREAD

**Issue by toasterfree** [BSData/catalogue-development#134]
I started working on, and finished the American army  and the base game system for  Team Yankee World War 3 and am ready to submit my first files.

**Comment by toasterfree** [comment]
[Team Yankee WW3.zip](https://github.com/BSData/catalogue-development/files/5212186/Team.Yankee.WW3.zip)
The base catalog and initial nation for the game

**Comment by Mad-Spy** [comment]
This repo is now ready to use. Your upload should use the unzipped .cat and .gst files in order for the release workflow to run properly.
