### ISSUE TITLE
New repo: Gaslands refueled French version

### ISSUE THREAD

**Issue by Kassbinette** [BSData/catalogue-development#135]
Hello 

I (heavily) adapted the english version of the gaslands data file to have a set of data usable with the new nice shiny french version  of the game. 

[Gaslands refueld Français.zip](https://github.com/BSData/catalogue-development/files/5191424/Gaslands.refueld.Francais.zip)

For publication on this git I removed the rules (as I understood it was not legit) 
Hope this will help 

Cheers

**Comment by Kassbinette** [comment]
[Gaslands refueld FR.zip](https://github.com/BSData/catalogue-development/files/5211501/Gaslands.refueld.FR.zip)
New version with some improvements like calculation of the maximal amount of crew members and the automatic increment of hull and maneuver points

**Comment by amis92** [comment]
@Kassbinette in regards to this specific request, please see #15 - currently we're not accepting translations, as it's not maintainable in current shape of BattleScribe.

I'm expecting you're not going to re-patch english files, though? :)

**Comment by Kassbinette** [comment]
Oh .... Damn ... Indeed I won't repatch them :D 
But if someone wants to, the files are there and I would be glad if they were as I think I've made some important improvements (though I still need to fix one or two things) 

BTW I think some mass find and replace could do the trick ...

**Comment by afraeve** [comment]
Hi, you might have to take the "ç" out of Français in the cat file titles - I had to take the "é" out of Ulthwé when I started on Epic - it appeared ok on github & appspot, but then it wouldn't download to my phone :(
