### ISSUE TITLE
enhancement: add a link to a css and a Javascript file in the generated html

### ISSUE THREAD

**Issue by Kassbinette** [BSData/catalogue-development#136]
It would be nice to be able to just save your html file in a directory where you would have saved your style and javascript file and have an adapted version of the html. 
Currently I performed this task with a tampermonkey script but it's quite a pain in the ass

**Comment by DrTobogganMD** [comment]
This is not a request for BSData, rather a request for a Battlescribe enhancement. Please raise an issue here: https://github.com/BattleScribe
