### ISSUE TITLE
enhancement : allow to select entries from shared entry group selection in catalogues

### ISSUE THREAD

**Issue by Kassbinette** [BSData/catalogue-development#137]
I noticed * that the software already allows the creation of rosters with that kind of entries 
this would allow a far better organisation of the data 

* by modifying directly the xml and moving the entries into entry groups after having created the catalogues
see gaslands refueled french version file (uploaded tonight )

**Comment by Mad-Spy** [comment]
Not sure what you mean here? Maybe a screenshot of the issue would help.

**Comment by toasterfree** [comment]
i think what Kass is getting as is being able to select unit A out of catalog A for a roster using catalog B

**Comment by Mad-Spy** [comment]
This is also possible, either by putting the units in the GST (where they will be available to _all_ catalogues), or by creating a Library catalogue and linking it into the necessary catalogues.

**Comment by amis92** [comment]
It'd be great if @Kassbinette could try to be a bit more specific.

**Comment by Kassbinette** [comment]
Hello 

Sorry for my previous message was totally unclear. 
I hope some pictures will help to clarify 

So I began to work on a translated version of the gaslands BSdata. 
At one point of the work, I was annoyed by the mess in the data : The vehicules were stored with the sponsors as shared selection entities.
I opened the xml and reorganised this in two shared entities group 
The result was this : 
![EntityGroups](https://user-images.githubusercontent.com/1396139/93096380-99957600-f6a4-11ea-8d9f-c15bb3629650.PNG)
 
Much cleared and far more organised 

No problem until now, I could still create rosters with no problem. 

When I went further in my revamp of the BSData, I arrived at a point where I imagined that it would be clearer to chose your sponsor as a force. So I created a new catalogue and  ... it wasn't possible to select the vehicules or the sposors anymore in a the catalogues. 
The reason is quite simple : you can only select the shared selection entries that aren't in a shared selection entity group (and that correspond to a catogery specified in the force definition) 

Though my previous catalogue still worked, so it means that with a little modificaion (allow the selection of shared entities stored in a group) you would have a better view on your data within the editor. 

 I finally modified the catalogues for my sponsors manually directly in the xml, and they are working fine (and my entities are still correctly organised) 

:) 

Here your are with the full explanation

**Comment by amis92** [comment]
@Kassbinette if I understand you correctly, you want "folders" for SSEs (shared selection entries) to have them nicely organized for when you're working with the data file (catalogue) - it doesn't have any effect on Roster Editor (when you actually build the rosters). Am I correct?

If so, that's generally a good idea to have, but it's not on current roadmap. I'd suggest raising a feature request on https://github.com/BattleScribe/Release/issues for "folders in catalogues" or something like that.

---

What you did I'm not sure, and how it works I don't understand even more - but what you need to understand is that Entries are what you work with, and Selection Groups are for applying constraints on a group of Entries. **Shared Selection Entry Groups** are for linking them into Links within Entries, for common selection choices like vehicle upgrades, army-wide options, etc.

**Comment by Mad-Spy** [comment]
@amis92 I think what he is saying is that you can't reference the Selection Entries that are inside SSEGs, because they are not themselves shared.

If you want to be able to reference items both as individual items AND from within an SSEG, you need to create them as SSEs and then link them into the SSEGs.

**Comment by amis92** [comment]
Oh, it's not `sponsors`, it's `sponsons`...

**Comment by cartag** [comment]
No, for Gaslands it's Sponsors.
