### ISSUE TITLE
Update name in appspot feed

### ISSUE THREAD

**Issue by rzmoz** [BSData/catalogue-development#145]
Hi, we just got a new repo called The-9th-Age-Essence-of-War which is great. It works and it's now public on appspot. But the name in the appspot list is The-9th-Age-Essence-of-War.

Is there a way we can change it to  The 9th Age: Essence of War?

**Comment by amis92** [comment]
Yes, edit the repo description.

![image](https://user-images.githubusercontent.com/2671396/97586042-192f9800-19fa-11eb-9ca2-c55172c60377.png)

**Comment by rzmoz** [comment]
Hi, thank you but I don't have access to edit the repo. Can you please grant me those permissions?

![image](https://user-images.githubusercontent.com/17024023/97640432-fffe0a00-1a40-11eb-9c52-b826d4c6f524.png)

**Comment by amis92** [comment]
I've increased your permission. Let me know if you're still unable to edit.
