### ISSUE TITLE
New repo:

### ISSUE THREAD

**Issue by Ergofarg** [BSData/catalogue-development#146]
I have a new repository list for Warhammer Fantasy Battle 6th edition.
This needs its own listing, not grouped with the other editions.
https://github.com/Ergofarg/Warhammer-Fantasy-6th-edition

**Comment by OftKilted** [comment]
Why does this edition need its own Catalog?

**Comment by Ergofarg** [comment]
All editions need their own catalogue. The one in the bs files makes you think it is just fourth on the read me, but someone has stuck 7th in there as well. I dont want to be inundated with catalogues of all the different editions, just the ones I want.

**Comment by OftKilted** [comment]
You select WHFB and you get the ability to create forces from 4th on up (depending on what you choose to make). If you have a properly created .gst that is unique and unique catalog files (with unique guids) then they can all exist together.

**Comment by Ergofarg** [comment]
Forget it. I will go my own way.

**Comment by Ergofarg** [comment]
Yet 9th age have their own.

**Comment by OftKilted** [comment]
“The 9th Age: Fantasy Battles” is a product that isn’t made by GW.  It was created by a volunteer organization based over on https://www.the-ninth-age.com

While it is a derivative of WarHammer Fantasy Battles, it is a different game.

All of the official editions of Warhammer Fantasy Battles were created by GW.

**Comment by Ergofarg** [comment]
It is still Warhammer Fantasy battle with fan made rules. 6th is a different game from 4th by a long way.
