### ISSUE TITLE
Warlords of Archaios

### ISSUE THREAD

**Issue by dariokoen** [BSData/catalogue-development#150]
I have a free game, were all terrain, miniatures, and the core rules are free to download and I'd like to add the stats and points to battlescribe. I use my youtube channel https://www.youtube.com/channel/UC8O2C4D0crs7LxVNuSMgE-g?view_as=subscriber to promote it. I think this would help me grow my project and help it feel more official let me know. Here' a link to the files as well https://drive.google.com/drive/folders/1BHFM1O92XCVQy3ilJhvQHLHRCYwSOP4P

**Comment by Mad-Spy** [comment]
Data files are created by volunteers, so you'll either need to create them yourself or find someone willing to do it for you. The best place to find help with creating files is on the Data Author Discord, https://discord.gg/KqPVhds
