### ISSUE TITLE
Named character and Relics of SW codex

### ISSUE THREAD

**Issue by Exfrau** [BSData/catalogue-development#153]
The Battlescribe 9.1.9 is missing all named characters for the HQ choices in a Adeptus Astartes - Space Wolve detachment. Furthermore there is no listing of relics out of the Space Wolve codex.

**Comment by Mad-Spy** [comment]
1. This should have been logged in BSData\wh40k.
2. Try selecting "Space Wolves" in the Chapter Selection options.
