### ISSUE TITLE
New Repo: Warhammer Age of Sigmar Warcry Spanish Translation

### ISSUE THREAD

**Issue by isorna** [BSData/catalogue-development#154]
Hi there, I'm Alvaro Isorna, part of the [Wargames Castellano community](https://discord.gg/tP8scYWa), we'd like to help non-english-speaking mates with an spanish traslation of this repository.

I've already forked it and reviewed on the data editor, I'll just wait for the release of the latest changes to start translating the data, but I'd like to know if it's possible to create a new repository for this translation.

Regards

**Comment by amis92** [comment]
We're not yet able to support translations. See #15
