### ISSUE TITLE
New Repo: Cruel Mistress

### ISSUE THREAD

**Issue by cynebald** [BSData/catalogue-development#157]
Looking to set up a new repository for Cruel Mistress : A Simple Naval Wargame if possible.

**Comment by Mad-Spy** [comment]
Can you add a link to the game?

**Comment by cynebald** [comment]
https://docs.google.com/document/d/1HZjg60aEdjT1vVv_88RV0ICD_LNHVVMAahzj1X1NlOE/edit?usp=sharing @Mad-Spy

**Comment by Mad-Spy** [comment]
As discussed, it's a bit early to add this one into the org, given it isn't released yet.
