### ISSUE TITLE
New repo: Chronopia

### ISSUE THREAD

**Issue by Chronopia** [BSData/catalogue-development#164]
Hi. 
I am working for Uhrwerk Verlag, company that bringing back Chronopia wargame to the table tops q4 of 2021. I would like to create a data file for that game for Battle Scribe. Just do not know where to start?

**Comment by amis92** [comment]
@Chronopia wiki linked above and the Discord server is a good start :) When you have some datafiles already please come back here and reopen this issue (and edit the title accordingly). Good luck!

**Comment by Chronopia** [comment]
Hi,

How can I upload files for Chronopia now?
It took some time before we have found somebody to create a data base for us, but how we can upload it now so it would be visible?

Next question - how could I connect other people for updating this files?

Best Regards
Editor-in-chief of Chronopia
Marcin Malinowski aka Martin Hood
Website<https://www.uhrwerk-verlag.de/> Facebook<https://facebook.com/groups/chronopia> Instagram<https://instagram.com/chronopia_> Youtube<https://www.youtube.com/channel/UCmipZ96cEkSZjg2vWv-XXBw/>

<https://www.uhrwerk-verlag.de/>


________________________________

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/3817863156)
