### ISSUE TITLE
New repo: Rogue Stars

### ISSUE THREAD

**Issue by Gus969** [BSData/catalogue-development#165]
Rogue Stars
[RogueStarsBattleScribeCleanv2.zip](https://github.com/BSData/catalogue-development/files/6326808/RogueStarsBattleScribeCleanv2.zip)

Stars BattleScribe datafile by Colby Chappell v 2.0

**Comment by amis92** [comment]
@Gus969 have you read the message above? Did you read wiki? Will you be able to upload the datafiles if we create the new repository for this game?

**Comment by amis92** [comment]
@Gus969 over one month. I'll close this issue now, but whenever you're active again, please reopen this :)

**Comment by Gus969** [comment]
Hi, sorry for the delay, I had some personal complications.
I cant mantain a repository of datafiles, I thought that was easy to put
files in public for rogue stars and battlescribe, there is a group on
facebook of fans of Rogue stars with more than 2000 people, I thought it
would be good, but thats ok, if you need a repository with an administrator
to upload this file, its ok to close the ticket, thanks.
