### ISSUE TITLE
New repo: Dystopian Wars 3.0

### ISSUE THREAD

**Issue by siponer** [BSData/catalogue-development#166]
I'm writing datafile per Dystopian Wars 3.0 game.
I have completed the first faction and I want to publish it.

Regard

**Comment by amis92** [comment]
Hi @siponer if you're interested in creating the datafiles for new edition, would you consider updating the old repository? https://github.com/BSData/dystopianwars

We try not to create new repositories for new editions of an existing game. :)

**Comment by amis92** [comment]
To be clear, I mean would you want to put your files in that repository (probably removing the old ones) and work there, or do you have some arguments to have a new repository.

**Comment by siponer** [comment]
Hello!! For me it's ok to continue using the old repository.
Of course my files will replace the old one, because the new one are very different, hoping noone wants them.
Let me know how I can continue and what I have to do with old files.
Thanks

**Comment by amis92** [comment]
Cool. Please open an appropriate issue over there: https://github.com/BSData/dystopianwars/issues/new?title=%5BJoin%20Request%5D

I'm pretty sure you can indeed completely remove the old files. After your Join Request you'll be provided with more links to helpful resources.
