### ISSUE TITLE
Joining Repository Updates Wiki

### ISSUE THREAD

**Issue by ragados** [BSData/catalogue-development#17]
A few suggested updates to the Wiki:

Added Repositories: (I would like to work on these)
- Warlord Games > Test of Honour
- Spartan Games > Uncharted Seas

Moving repositories:
- Deadzone > Mantic Games
- Warpath > Mantic Games

Open questions:
- Spartan Games no longer exists. Most of the game systems now sit with Wayland Games (who also produce Wild West Exodus - possibly restructure these together) - Only the Halo Games did not transfer over tmk - source: https://www.youtube.com/watch?v=gHJ3eoXhxAg
- Fantasy Flight Games do all listed Star Wars games as well as Rune Wars - would it make more sense to move these all under a Fantasy Flight Games label? (I appreciate this causes some issues for the likes of Warhammer Diskwars but again I'd look for that under FFG ahead of GW).

*Disclaimer - I'm new to this community so apologies if this is the wrong way to go about things. I read through what I could find and made a best guess.

**Comment by amis92** [comment]
Yeah, thanks very much! All good points.

I guess you'd like to create datafiles for these two listed as "Added"?

So, Halo games: it's dead, then?

FFG will make more sense. Diskwars I just didn't do the research and categorized by name (Warhammer ;) ) - also that's dead too, since FFG got rejected by GW?

**Comment by ragados** [comment]
Would be happy to create the data files for those two. I am working on Test of Honour at the moment as it's a simpler prospect. May take a while to get to Uncharted Seas.

Halo games are no longer being supported tmk.
Diskwars is also dead - FFG lost the GW license.

**Comment by amis92** [comment]
Okay. Then I'll ask you to open a new issue here with a request to create a repository for a game system when you have something ready. :)
