### ISSUE TITLE
New repo: Reign in Hell

### ISSUE THREAD

**Issue by Zanchito** [BSData/catalogue-development#170]
New skirmish game by Vince Venturella and Uncle Atom

**Comment by cartag** [comment]
If you haven't started the data yet, I've got great news: I've already written a file for it that just needs QA (I'm one of the main data authors on AoS). I was waiting on the person who created the repo to do more with it, but that hasn't happened. Once the repo gets created I can upload mine and we can go from there. If you don't mine.

**Comment by Zanchito** [comment]
I have indeed started the data, but if you have more experience and are only waiting for QA, I'd gladly defer to you.

**Comment by cartag** [comment]
I was the initial creator of the Gaslands data file, have been the overseer of the AoS change from 2.0 to 3.0, I have a little experience ;) 

![image](https://user-images.githubusercontent.com/4388344/124949663-003aa600-dfcf-11eb-88d8-03279650b844.png)
