### ISSUE TITLE
New Repo: Renegade Scout

### ISSUE THREAD

**Issue by Miniatorium** [BSData/catalogue-development#174]
As the title says, I'd love to make a repo for this overlooked gem from Nordic Weasel Games.

**Comment by Miniatorium** [comment]
Ah shoot - the invitation expired before I could get around to it. Was knocked out by a heavy cold :(

Could I get a re-invite?

**Comment by amis92** [comment]
Done

**Comment by Miniatorium** [comment]
Thank you kindly!
