### ISSUE TITLE
New repo: Warmaster Evolution

### ISSUE THREAD

**Issue by BenChab** [BSData/catalogue-development#179]
Hi, i would like to work on a repository for the game Warmaster Evolution.
It doesn't seems to be any data for the game yet.
Thanks

**Comment by amis92** [comment]
This falls under #86 - please follow our guide at https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories to create a self-hosted repository.

If your work has a good quality, please apply for inclusion in our Gallery project at: https://github.com/BSData/gallery
