### ISSUE TITLE
Compressed Files still not permitted?

### ISSUE THREAD

**Issue by ragados** [BSData/catalogue-development#18]
@amis92 

Is this still true?
Don't add compressed files (*.gstz, *.catz) - save them as *.gst and *.cat instead (Save as... in Files menu in Editors).
Source: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide#most-common-mistakes

I see a lot of compressed files when downloading.

**Comment by Obiken** [comment]
Still true, files are compressed when served from the BSData site.

**Comment by amis92** [comment]
Added explanation to the wiki.
