### ISSUE TITLE
New Repo: Warmaster Revolution

### ISSUE THREAD

**Issue by TomRome2Rio** [BSData/catalogue-development#180]
I want to create a BS repo for Warmaster Revolution (as opposed to the confusingly similarly-named "Warmaster Evolution")

I have already started on the repo [here](https://github.com/TomRome2Rio/WarmasterBattlescribe)

**Comment by amis92** [comment]
This falls under #86 - please follow our guide at https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories to create a self-hosted repository.

If your work has a good quality, please apply for inclusion in our Gallery project at: https://github.com/BSData/gallery
