### ISSUE TITLE
Old repo: Warhammer 40k 9th edition

### ISSUE THREAD

**Issue by dncnmcdougall** [BSData/catalogue-development#182]
Hi,
thank you for all the hard work making BattleScribe a seamless and wonderful experience!

I have just reinstalled it on a new computer and cannot find Warhammer 40k 9th edition. There are 8th and 7th editions, but 9th seems to be missing.
This can also be seen on the main sight:
(https://battlescribedata.appspot.com/#/repos) where 9th edition is not listed.
I tried linking manually with:
(https://battlescribedata.appspot.com/repos/wh40k/index.bsi)
but get a 404 not found error.

I expect that this is a small problem as the wh40k repo is still live an frequently updated.

Thank you for your help.

**Comment by OftKilted** [comment]
Not an issue. On some refreshes app spot can hiccup and temporarily looses the repo. 

Please use:

http://battlescribedata.appspot.com/#/repo/wh40k

**Comment by dncnmcdougall** [comment]
Excellent!
