### ISSUE TITLE
New repo: Halo: Reclaimer

### ISSUE THREAD

**Issue by Arkimian** [BSData/catalogue-development#188]
Hi! I'm the sole Community Contributor working on Halo: Reclaimer with a pair of other developers. We'd like to host our game system on Battlescribe, and I have already made the requisite files and solidified them as a Battlescribe repository.

**Comment by amis92** [comment]
Please provide a link to the game or publisher website. Thanks!

**Comment by Mad-Spy** [comment]
Closing due to lack of response
