### ISSUE TITLE
New repo:  Warhammer 40K: Crusade 

### ISSUE THREAD

**Issue by raphyand** [BSData/catalogue-development#191]
I'd like to try making a new system in battle scribe to support 9th Edition Crusade.  I looked through other apps and I feel like it would be nice to have a Crusade System on BattleScribe.  Incorporating Data on every army and having sections keep track of your rostered units, xp, etc. would be great to have in BattleScribe, and I'd like to take a crack at it, if allowed!

**Comment by Mad-Spy** [comment]
There's a reason that the current data Devs have not done this already. It's basically because BS is unable to support it, both due to the load on the engine and because of poor support for volatile data (especially profile changes).

If you want to discuss further, please jump on to Discord.
