### ISSUE TITLE
Unarchive Repo: Konflikt 47

### ISSUE THREAD

**Issue by ingeanus** [BSData/catalogue-development#192]
Since the [archived Konflikt 47 repo](https://github.com/BSData/konflikt47) hasn't been updated in 3 years, I've been implementing the data under the [ingeanus/konflikt47](https://github.com/ingeanus/konflikt47) fork of it, and want to see about it getting unarchived and/or set as the main repo, or something to that effect.

**Comment by amis92** [comment]
@ingeanus sure, we can do that. Have you looked at the `develop` branch? There was some work, but the author never merged to `master`, and never published this.

**Comment by ingeanus** [comment]
I have indeed. I've only got it stored locally currently, because the incomplete files were causing errors when importing into the Roster Editor, but I've been using them as a jumping off point.

**Comment by Mad-Spy** [comment]
@ingeanus I've unarchived the repo and made you a maintainer on it so you can upload your changes and release them.
