### ISSUE TITLE
New repo: Alternate 40k Rules

### ISSUE THREAD

**Issue by Alternate40kRules** [BSData/catalogue-development#193]
Greetings in the name of the Emperor! A small team under my leadership has spent almost 1 year and 1700 man hours rewriting the 40k rules from scratch using rules from rogue trader to present day, as well as homebrew rules. We nearly have every codex rough drafted and many in the final stages of development. Unlike games-workshop, we actually test pur rules extensively, use formulas for statlines, and try to make every unit abd character as lore accurate as possible. I would love to host our files for free for the world to use on battlescribe. While we are a ways off still, beginning the intoduction of the corebook and refined codexes now would make the publication easier. Feel free to check out our website at alternate40krules.wordpress.com. I am still working on getting a professional photographer for the showcase pages, but read our narrative battle reports and watch our video battle reports to see how much fun we are having!

**Comment by Mad-Spy** [comment]
Please see the Github hosting instructions here: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

The BSData repository does not currently allow fanmade content, only officially released game systems.
