### ISSUE TITLE
New repo: Anima Tactics

### ISSUE THREAD

**Issue by SulLind** [BSData/catalogue-development#195]
Anima Tactics miniature skirmish game made by Cipher Studios.

**Comment by Mad-Spy** [comment]
Please provide a link to the game's website.

**Comment by SulLind** [comment]
Pretty difficult thing to do, cause game was discontinued more than 7 years ago and related official websites was shutdown soon after.
Best links that i was able to find now:
https://twitter.com/cipherstudios
https://boardgamegeek.com/boardgame/27028/anima-tactics
https://www.tabletopgamingnews.com/tag/cipher-studios
Starter rulebook:
https://drive.google.com/file/d/0B8oFHTYFP9q1YXp2NVQ5OGxuVzQ/view?usp=sharing&resourcekey=0-Xzl_OWR5DHj_nu1EqYxSvA
https://images-cdn.fantasyflightgames.com/ffg_content/Anima%20Tactics/Site/tactics%20rulebook%20english.pdf
https://fdocuments.in/document/anima-tactics-rulebook.html?page=1
Core rulebook (without lore part): https://fdocuments.in/document/anima-tactics-rules.html
Anima Tactics Oracle: http://atoracle.wikidot.com/en-rulebooks

**Comment by Mad-Spy** [comment]
Given that the game is no longer commercially available, I suggest you self-host via Github. Details on how to do this can be found at the following link.
https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
