### ISSUE TITLE
Rename deadzone repo

### ISSUE THREAD

**Issue by KurganFr** [BSData/catalogue-development#196]
The BSData/deadzone repo is entitled "Deadzone 2nd Edition" but it now contains 3rd edition data files also.

![image](https://user-images.githubusercontent.com/1501366/172075235-3fd5385b-7025-449b-9542-2579bf2bb6ea.png)

Can the title please be updated to "Deadzone by Mantic Games"? This would significantly reduce confusion for users.

I asked for this to be done back in January (https://github.com/BSData/deadzone/issues/55) but nobody in the deadzone repo who has access to do so has picked up on my request.

Thanks in advance.

**Comment by Mad-Spy** [comment]
Done
