### ISSUE TITLE
New Repo: Elder Scrolls: Call To Arms

### ISSUE THREAD

**Issue by holliewillow** [BSData/catalogue-development#197]
name: TES-Call-To-Arms
I have made datafiles for The Elder Scrolls: Call To Arms. They are ready, could you please host them? This is the URL: https://github.com/holliewillow/TES-Call-To-Arms-Battlescribe/releases/latest/download/TES-Call-To-Arms-Battlescribe.latest.bsi
I can also send the files if needed.

Thank you,
sapphicmoon

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/2482260986)
