### ISSUE TITLE
New repo: Blood & Steel

### ISSUE THREAD

**Issue by Shannegh** [BSData/catalogue-development#198]
Rule system - Blood & Steel Victorian Age Combat 1837-1901
Producer - Firelock Games (https://www.firelockgames.com/)

Same family of games as Blood & Valor game system, but standalone system.
I have already built the initial .gst and .cat files and have them ready to roll on Github Desktop app.

**Comment by Shannegh** [comment]
@amis92 not sure if I am supposed to tag you in this. Apologies if I'm doing this wrong.

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/2608792622)
