### ISSUE TITLE
New repo: Clash of Katanas

### ISSUE THREAD

**Issue by sunabe** [BSData/catalogue-development#199]
Hi BattleScribe people,

I wrote a file for the new Clash of Katanas system. It should be close to finished
I'm not affiliated with Fighting hedgehog (https://www.fightinghedgehog.com/) the owners of this rule system. 
I made this with the advance copy I had through the Kickstarter.
You can find it on here on Github at https://github.com/sunabe/Clash-of-Katanas
What are the following steps?

the following ling is to the bsr file
https://www.dropbox.com/s/mh0drc0j94g01yj/Clash%20of%20Katanas.bsr?dl=0

In kind regard,

Sunabe/Karter Aurian

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/2608793691)
