### ISSUE TITLE
Feedback waiting time

### ISSUE THREAD

**Issue by Kangodo** [BSData/catalogue-development#2]
In /40k we have a lot of open issues.
These stay open because the last post asks for more feedback or wants to know if something is fixed.

I would like to propose a maximum waiting time for these kind of open issues.
If a user hasn't responded in 7 days, we can assume that the issue is fixed or that someone else will report the issue again with more clarification.

What do you think about this?
It's time to clean up those issues! :)

**Comment by amis92** [comment]
Closed because of age
