### ISSUE TITLE
New repo: Gamma Wolves

### ISSUE THREAD

**Issue by Fleafa** [BSData/catalogue-development#201]
I've made a start on a Gamma Wolves Repo. All initial validation and profiles are in. Just need to start on rules text.

**Comment by Fleafa** [comment]
Whoops, misread the "(BSData organization owner only)" part there, sorry!

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/2944081154)
