### ISSUE TITLE
New repo: Warhammer 40,000 - 2nd Edition

### ISSUE THREAD

**Issue by Boff89** [BSData/catalogue-development#204]
name: wh40k-2nd-edition

https://github.com/Boff89/40k2ndEd

Hope I did this right. I have put the files in the repo link above but am new to Github

**Comment by Mad-Spy** [comment]
/preview
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/3292439268)
### ⚙ Setup preview

**Repository name:** `warhammer-40-000-2nd-edition`

**Repository description:** `wh40k-2nd-edition`

**Collaborators to invite:** `@Boff89`

If you'd like to change either of these:
* **name** is taken from the first line of the issue body if it starts with a `name: ` prefix, or if it doesn't,
 by normalizing the **description** with some simple regex. To change, add a first line in format
 `name: example-repo-name` in the issue body.
* **description** is taken from the issue title, skipping `New Repo: ` prefix - to change, edit issue title.
* **collaborators** should include request author (OP).

Comment `/preview` to request this check again.

(**BSData organization owner only**): Comment `/approve` to create the new repository as shown above.

#### 📝 Important information

Don't forget to read through [wiki][], there are some useful guides - especially [Data Author Guide][guide].

#### 📲 Join Community

Join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://www.bsdata.net/discord)

Cheers!

---
Yours truly, @BSData-bot.

[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by Mad-Spy** [comment]
/preview
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/3292449811)
### ⚙ Setup preview

**Repository name:** `wh40k-2nd-edition`

**Repository description:** `Warhammer 40,000 - 2nd Edition`

**Collaborators to invite:** `@Boff89`

If you'd like to change either of these:
* **name** is taken from the first line of the issue body if it starts with a `name: ` prefix, or if it doesn't,
 by normalizing the **description** with some simple regex. To change, add a first line in format
 `name: example-repo-name` in the issue body.
* **description** is taken from the issue title, skipping `New Repo: ` prefix - to change, edit issue title.
* **collaborators** should include request author (OP).

Comment `/preview` to request this check again.

(**BSData organization owner only**): Comment `/approve` to create the new repository as shown above.

#### 📝 Important information

Don't forget to read through [wiki][], there are some useful guides - especially [Data Author Guide][guide].

#### 📲 Join Community

Join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://www.bsdata.net/discord)

Cheers!

---
Yours truly, @BSData-bot.

[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/3292455041)
