### ISSUE TITLE
New repo: Shattered Realms

### ISSUE THREAD

**Issue by smurfsoden** [BSData/catalogue-development#206]
Hi, 

I am developing my own Miniature Wargame called Shattered Realms. The game is being play tested at the moment and I am attempting to reach other play testers. I have created a Battlescribe file to play as all current factions in the game that I would like to host for the battlescribe app for users to easily access it.

If you want to know more about the game you can visit here: https://charliesoden.wixsite.com/sodengames/shattered-realms where you can view the rules.

Thanks,
-Charlie (Soden Games)

[Shattered Realms.zip](https://github.com/BSData/catalogue-development/files/9947061/Shattered.Realms.zip)

**Comment by OftKilted** [comment]
Please refer to issue #86 for fan-created repo and games to allow you to better support players.
