### ISSUE TITLE
New repo: Seven Days to the River Rhine

### ISSUE THREAD

**Issue by dstretch** [BSData/catalogue-development#207]
Hi there,

I've been working on BS data for SDttRR and would like to have the repo hosted by yourselves so it's available to anyone interested without having to add custom files manually on their device.

Is there anything specific I need to do for this?  The repo was cloned from your Template repo and already has an alpha release in it.

Thanks

**Comment by dstretch** [comment]
Oh, I've just seen this: https://github.com/BSData/catalogue-development/issues/86.  I guess it's not going to happen then :(

**Comment by Mad-Spy** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
