### ISSUE TITLE
How to reopen this issue?

### ISSUE THREAD

**Issue by Chronopia** [BSData/catalogue-development#208]
**Is your feature request related to a problem? Please describe.**
I finally have a data files to upload. I would like to reopen this issue, reopen my repo and upload files, please.

New repo: New game system data (Chronopia) #164

**Comment by Mad-Spy** [comment]
#164 has been reopened. Please update it as per the automatic reply.

**Comment by Chronopia** [comment]
Ok,

How can I upload those files to my repo?


Best Regards
Editor-in-chief of Chronopia
Marcin Malinowski aka Martin Hood
Website<https://www.uhrwerk-verlag.de/> Facebook<https://facebook.com/groups/chronopia> Instagram<https://instagram.com/chronopia_> Youtube<https://www.youtube.com/channel/UCmipZ96cEkSZjg2vWv-XXBw/>

<https://www.uhrwerk-verlag.de/>


________________________________
