### ISSUE TITLE
New repo: Adeptus Titanicus 2018 

### ISSUE THREAD

**Issue by capitaladot** [BSData/catalogue-development#21]

**Comment by capitaladot** [comment]
Files ready to commit/push.

**Comment by amis92** [comment]
@capitaladot should this be called Horus Heresy: Adeptus Titanicus, or just Adeptus Mechanicus?

**Comment by capitaladot** [comment]
It is a totally separate system. I would just call it Adeptus Titanicus
2018 (since there was an '88 version).

**Comment by capitaladot** [comment]
The '88 version is the original Horus Heresy game, oddly enough.

**Comment by amis92** [comment]
Okay. I ask, because to date, most associated Warhammer or Warhammer 40,000 systems had that prefix in the game system name.

**Comment by capitaladot** [comment]
I would say let's leave it out.

**Comment by amis92** [comment]
Okay, here goes: https://github.com/BSData/adeptus-titanicus
