### ISSUE TITLE
Using template repo - cannot properly create release

### ISSUE THREAD

**Issue by MikeokeBS** [BSData/catalogue-development#212]
Trying to build a repo release for self made datafiles.

When creating release, only zip files are created.

Actions log shows Issue with ci.yml:
[build](https://github.com/MikeokeBS/HailCaeserv0.1/actions/runs/3968497183/jobs/6801737732#step:4:6)
Path does not exist /home/runner/work/_temp/assets

[build](https://github.com/MikeokeBS/HailCaeserv0.1/actions/runs/3968497183/jobs/6801737732#step:4:7)
Exit code 1 returned from process: file name '/home/runner/runners/2.300.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'

**Comment by Mad-Spy** [comment]
You need to upload cat and gst files to your repo, not the bsr, as per the guidance here - https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories#hosting-custom-repositories
