### ISSUE TITLE
Error when creating a Release - Using template repo from BSData

### ISSUE THREAD

**Issue by MikeokeBS** [BSData/catalogue-development#213]
When trying to create a release, only 2 zip files drop, with no other files.  All steps in FAQ have been taken.
mikeokebs/hailcaesar and mikeokebs/hailcaesarproject

Error fails during publish segment when invoking rest method:

Run BSData/publish-catpkg@v1

Run $ErrorActionPreference = 'Stop'
dotnet tool install wham --version 0.13.0 --tool-path "$PSScriptRoot/lib"
You can invoke the tool using the following command: wham
Tool 'wham' (version '0.13.0') was successfully installed.
& $wham publish -a zip -o $StagingPath
[19:41:3[6](https://github.com/MikeokeBS/HailCaesar/actions/runs/3970755374/jobs/6806847301#step:3:7) INF] Creating artifact: ZippedXmlDatafiles
[19:41:36 INF] Created /home/runner/work/_temp/assets/Hail Caeser.gstz
[19:41:37 INF] Created /home/runner/work/_temp/assets/Thematic Byzantine.catz
[19:41:37 INF] Created /home/runner/work/_temp/assets/Arthurian Britain.catz
Staged 'Arthurian Britain.cat' as 'Arthurian.Britain.catz'
Staged 'Hail Caeser.gst' as 'Hail.Caeser.gstz'
Staged 'Thematic Byzantine.cat' as 'Thematic.Byzantine.catz'
& $wham publish -a bsr -f $taggedAssetNameEscaped --repo-name $repoName
[19:41:37 INF] Creating artifact: RepoDistribution
[19:41:37 INF] Created /home/runner/work/_temp/assets/HailCaesar.v0.1.bsr
& $wham publish -a bsi -f $taggedAssetNameEscaped --repo-name $repoName --url $tagBsiUrl
[19:41:38 INF] Creating artifact: ZippedIndex
[19:41:38 INF] Created /home/runner/work/_temp/assets/HailCaesar.v0.1.bsi
& $wham publish -a bsi -f $latestAssetNameEscaped --repo-name $repoName --url $latestBsiUrl
[19:41:38 INF] Creating artifact: ZippedIndex
[19:41:38 INF] Created /home/runner/work/_temp/assets/HailCaesar.latest.bsi
Invoke-RestMethod: {"message":"Resource not accessible by
integration","request_id":"[34](https://github.com/MikeokeBS/HailCaesar/actions/runs/3970755374/jobs/6806847301#step:3:36)05:2E9B:D1AE7:15EEFD:63CAEE8E","documentation_url":
"https://docs.github.com/rest"}

Error: Process completed with exit code 1.

**Comment by MikeokeBS** [comment]
It looks like there was also an error when copying the template in the first place:

ci.yml
<html>
<body>
<div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: var(--base-size-4, 4px)  !important; margin-bottom: var(--base-size-16, 16px)  !important; padding-right: var(--base-size-16, 16px)  !important; padding-left: var(--base-size-16, 16px)  !important;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: var(--base-size-4, 4px)  !important; margin-left: var(--base-size-4, 4px)  !important;"><h4 class="text-bold" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: var(--h4-size, 16px); font-weight: var(--base-text-weight-semibold, 600)  !important;">Annotations</h4><div class="color-fg-muted text-small" style="box-sizing: border-box; color: var(--color-fg-muted)  !important; font-size: var(--h6-size, 12px)  !important;">2 errors and 1 warning</div></div></div><table class="width-full mt-n1 actions-workflow-table table-fixed" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; width: 846px; margin-top: calc(-1*var(--base-size-4, 4px))  !important; table-layout: fixed !important;"><tbody style="box-sizing: border-box;"><tr role="row" style="box-sizing: border-box;"><td class="compact pr-3 col-7 col-lg-9 color-border-muted border-bottom" style="box-sizing: border-box; padding: 12px 20px; width: 846px; border-bottom-width:  !important; border-bottom-style:  !important; border-color: var(--color-border-muted)  !important; height: 48px; line-height: 20px;"><annotation-message class="d-flex" data-catalyst="" style="box-sizing: border-box; display: block;"><div style="box-sizing: border-box;"><svg class="octicon octicon-x-circle-fill mr-2 color-fg-danger" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M2.343 13.657A8 8 0 1113.657 2.343 8 8 0 012.343 13.657zM6.03 4.97a.75.75 0 00-1.06 1.06L6.94 8 4.97 9.97a.75.75 0 101.06 1.06L8 9.06l1.97 1.97a.75.75 0 101.06-1.06L9.06 8l1.97-1.97a.75.75 0 10-1.06-1.06L8 6.94 6.03 4.97z"></path></svg></div><div class="ml-1 overflow-hidden" style="box-sizing: border-box; overflow: hidden !important; margin-left: var(--base-size-4, 4px)  !important;"><a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/MikeokeBS/HailCaesar/actions/runs/3970731523/jobs/6806797212#step:4:6" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg)  !important; text-decoration: underline; display: block !important;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">build</strong></a><div class="color-fg-muted" style="box-sizing: border-box; color: var(--color-fg-muted)  !important;"><div data-target="annotation-message.annotationContainer" class="text-small text-mono annotation--contracted" style="box-sizing: border-box; font-size: var(--h6-size, 12px)  !important; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace !important;"><div style="box-sizing: border-box; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">Path does not exist /home/runner/work/_temp/assets</div></div></div></div></annotation-message></td></tr><tr role="row" style="box-sizing: border-box;"><td class="compact pr-3 col-7 col-lg-9 color-border-muted border-bottom" style="box-sizing: border-box; padding: 12px 20px; width: 846px; border-bottom-width:  !important; border-bottom-style:  !important; border-color: var(--color-border-muted)  !important; height: 48px; line-height: 20px;"><annotation-message class="d-flex" data-catalyst="" data-expanded="" style="box-sizing: border-box; display: block;"><div style="box-sizing: border-box;"><svg class="octicon octicon-x-circle-fill mr-2 color-fg-danger" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M2.343 13.657A8 8 0 1113.657 2.343 8 8 0 012.343 13.657zM6.03 4.97a.75.75 0 00-1.06 1.06L6.94 8 4.97 9.97a.75.75 0 101.06 1.06L8 9.06l1.97 1.97a.75.75 0 101.06-1.06L9.06 8l1.97-1.97a.75.75 0 10-1.06-1.06L8 6.94 6.03 4.97z"></path></svg></div><div class="ml-1 overflow-hidden" style="box-sizing: border-box; overflow: hidden !important; margin-left: var(--base-size-4, 4px)  !important;"><a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/MikeokeBS/HailCaesar/actions/runs/3970731523/jobs/6806797212#step:4:7" style="box-sizing: border-box; background-color: transparent; color: var(--color-fg-muted)  !important; text-decoration: none !important; display: block !important;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">build</strong></a><div class="color-fg-muted" style="box-sizing: border-box; color: var(--color-fg-muted)  !important;"><div data-target="annotation-message.annotationContainer" class="text-small text-mono annotation--expanded" style="box-sizing: border-box; font-size: var(--h6-size, 12px)  !important; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace !important;"><div style="box-sizing: border-box; word-break: break-word; white-space: pre-wrap;">Exit code 1 returned from process: file name '/home/runner/runners/2.300.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.</div></div><button data-action="click:annotation-message#toggleExpansion" data-target="annotation-message.showLessButton" class="btn-link text-normal" type="button" style="box-sizing: border-box; font-style: inherit; font-variant: inherit; font-weight: var(--base-text-weight-normal, 400)  !important; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; margin: 0px; overflow: visible; text-transform: none; appearance: button; cursor: pointer; border-radius: 0px; display: inline-block; padding: 0px; color: var(--color-accent-fg); text-decoration: none; white-space: nowrap; user-select: none; background-color: transparent; border: 0px;">Show less</button></div></div></annotation-message></td></tr><tr role="row" style="box-sizing: border-box;"><td class="compact pr-3 col-7 col-lg-9 color-border-muted" style="box-sizing: border-box; padding: 12px 20px; width: 846px; border-color: var(--color-border-muted)  !important; height: 48px; line-height: 20px;"><annotation-message class="d-flex" data-catalyst="" style="box-sizing: border-box; display: block;"><div style="box-sizing: border-box; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><svg class="octicon octicon-alert mr-2 color-fg-attention" style="margin-top: 1px" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.22 1.754a.25.25 0 00-.44 0L1.698 13.132a.25.25 0 00.22.368h12.164a.25.25 0 00.22-.368L8.22 1.754zm-1.763-.707c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0114.082 15H1.918a1.75 1.75 0 01-1.543-2.575L6.457 1.047zM9 11a1 1 0 11-2 0 1 1 0 012 0zm-.25-5.25a.75.75 0 00-1.5 0v2.5a.75.75 0 001.5 0v-2.5z"></path></svg></div><div class="ml-1 overflow-hidden" style="box-sizing: border-box; overflow: hidden !important; margin-left: var(--base-size-4, 4px)  !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>Annotations
2 errors and 1 warning
[build](https://github.com/MikeokeBS/HailCaesar/actions/runs/3970731523/jobs/6806797212#step:4:6)
Path does not exist /home/runner/work/_temp/assets
[build](https://github.com/MikeokeBS/HailCaesar/actions/runs/3970731523/jobs/6806797212#step:4:7)
Exit code 1 returned from process: file name '/home/runner/runners/2.300.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

**Comment by amis92** [comment]
@MikeokeBS it looks like it worked for you. Sorry I've not taken this up before. Was it the Actions permissions? If so, I've added the missing information now: https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

Sorry for the missing info, GitHub has relatively recently changed to new defaults that require additional action.
