### ISSUE TITLE
New Game System & Multiple Catalogue/Army files - NetEpic/Epic Space Marine 2nd Edition

### ISSUE THREAD

**Issue by SamwiseOfCat** [BSData/catalogue-development#216]
### Reference contact

@amis92

### Your Discord

stagletto

### Additional information

Hi there - ive spent a fair bit of time recently creating the core rules and army files for MOST of the races available for NetEpic/Space Marine 2nd Edition. This ruleset is very much still alive within the Epic community and as such ive tried to recreate it all in BS for modern convenience.

Please can you add me as a contributor so I can upload the necessary files for everyone out there to use :)

@amis92 apologies for tagging you as I havent spokenj to you directly, but it seems like you seem to be the one to contact in regards to getting stuff added to BS? MadSpy helped me on Discord with a few things. 

Thanks!
Samwise/Stagletto

**Comment by OftKilted** [comment]
Please see issue #86 for Hosting fanmade/alternate/community/[put sth here] rulesets and datafiles

**Comment by SamwiseOfCat** [comment]
Noted - thanks -
