### ISSUE TITLE
New repo: Zona Alfa V1

### ISSUE THREAD

**Issue by AnimaetAnimus** [BSData/catalogue-development#219]
I have made the first iteration of the battlescribe game system for Zona Alfa. It needs playtesting and balancing but right now it's functional. I would like to integrate it so I can get more feedback from the Zona Alfa communities.

**Comment by Mad-Spy** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
