### ISSUE TITLE
New repo: Batman Miniature Game

### ISSUE THREAD

**Issue by F4lconer** [BSData/catalogue-development#22]
Hello,

I'd like to create repo for Batman Miniature Game from Knight models.

**Comment by amis92** [comment]
There is one already, although it seems no one actually did anything there: https://github.com/BSData/batman

However from this discussion I've had: https://github.com/BSData/bsdata/issues/130 it'd seem that [DC Universe]() already contains Batman?

**Comment by F4lconer** [comment]
Good point I missed the Batman repo (althought only with readme) so no sense creating a new one. Sorry my bad.

I've briefly read the discussion, when I look into DC Universe, there is not catalogue for Batman Miniature Game. 
Technically speaking Batman as character is in both games, you can use the same mini, but the game systems are different.

In the end I will send join request for Batman repo to get started.

**Comment by amis92** [comment]
Great! Thanks for info.
