### ISSUE TITLE
[Join Request] Holotythe

### ISSUE THREAD

**Issue by DenOfImagination** [BSData/catalogue-development#221]
### Your Discord

misiek

### Additional information

I'm trying struggling with creating my own game system for BS, already got basic functionality in place, now I wish to get it available in app without pasting link to my github repo.

**Comment by Mad-Spy** [comment]
Please see the details on how to self host.
https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

**Comment by amis92** [comment]
Duplicate of https://github.com/BSData/catalogue-development/issues/223
