### ISSUE TITLE
New repo: Holotythe

### ISSUE THREAD

**Issue by DenOfImagination** [BSData/catalogue-development#222]
name:Holotythe
Repository: https://github.com/DenOfImagination/Holotythe

I'm not sure if I'm doing things right. I've created a gamesystem and repository on github, now I'm wondering how to take another step :) Sorry if I'm too dumb ;)

**Comment by OftKilted** [comment]
Holotythe appears to be a fanmade/alternate/community created rule set.

Please see issue https://github.com/BSData/catalogue-development/issues/86 for rules on these types of rule sets.

**Comment by amis92** [comment]
Duplicate of https://github.com/BSData/catalogue-development/issues/223
