### ISSUE TITLE
New repo: Holotythe

### ISSUE THREAD

**Issue by DenOfImagination** [BSData/catalogue-development#223]
### Reference contact

@Amadeusz

### Your Discord

misiek

### Additional information

I'm not fully sure of what I'm doing, but my goal is to publish my gamesystem for BattleScribe. I've asked some questions on discord and it brought me here.

**Comment by amis92** [comment]
Is this associated? https://github.com/BSData/catalogue-development/issues/220

**Comment by DenOfImagination** [comment]
> Is this associated? [BSData/catalogue-development#220](https://github.com/BSData/catalogue-development/issues/220)

Actually it is, as I'm trying to publish my gamesystem on Battlescribe :)

**Comment by amis92** [comment]
@DenOfImagination as all the other issues have explained, we don't generally create repositories in our organization for fanmade/community projects. However, we can still welcome you to our Gallery index: https://github.com/BSData/gallery

You need to add a new file within registry/entries path: https://github.com/BSData/gallery/tree/master/registry/entries

e.g. create a file `holotythe.catpkg.yml` with the following content:

```yaml
location:
  github: DenOfImagination/Holotythe
```

**Comment by amis92** [comment]
If you have further questions, don't hesitate! I'll try to answer.
