### ISSUE TITLE
New repo: The Doomed

### ISSUE THREAD

**Issue by DaeronAlagos** [BSData/catalogue-development#227]
name: the-doomed

**Comment by DaeronAlagos** [comment]
Data files ready to go 👍🏻

**Comment by amis92** [comment]
@DaeronAlagos can you link a website for the game?

**Comment by DaeronAlagos** [comment]
It's another osprey game

https://ospreypublishing.com/uk/doomed-9781472854261/

I wasn't going to bother but there seems to be some desire for a list builder in the FB group.

**Comment by amis92** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/6122344541)
