### ISSUE TITLE
Middle Earth Strategy Battle Game - Start from fresh or pick up Hobbit?

### ISSUE THREAD

**Issue by Zhaph** [BSData/catalogue-development#23]
Hi,

I'm interested in working on the Middle Earth Strategy Battle Game from GW that's released today - and think I can probably base it on the existing (sadly now abandoned) Hobbit edition.

I just wondered if there's a recommended/preferred way of doing this that won't upset/impact too much.

Option 1:

1. Work within the Hobbit.gst and update name, etc.

Option 2:

1. Create a new repo for the MESBG, rename the Hobbit.gst, and update names, etc.

I assume if I go with option 2 I should update the `unique id` of each component so that they don't clash with those from the Hobbit, or is that less important (i.e. only need to be unique within a game system)

Thanks in advance,

Ben

**Comment by Zhaph** [comment]
Having read the into now, it looks like Option 1 might be better as it states:

> **What about The Hobbit?**
>
> [...] all of the profiles, army lists, rules and Scenarios that focus on The Hobbit are presented in The Armies of the Hobbit. [That] works in much the same way as this manual, and is fully compatible with the Middle-earth Strategy Battle Game.

Indeed some of the army lists refer to options in those lists (notably The Kingdom of Kazad-Dûm).

**Comment by amis92** [comment]
I believe they intend to support Middle Earth as a rebranding, so probably creating new repository is in order. Indeed, you'll have to change game system ID (and thus switch it in every catalogue as well - it requires manual editing of XML) - but none other, since gst id acts as a root context for catalogues (so they won't clash with original Hobbit. It's a good time to reset revisions, update names, filenames etc, and of course probably rework the force organization, with a perspective of expansions like Hobbit, Gondor, LotR etc.

**Comment by Zhaph** [comment]
I've started work in [a fork of The Hobbit](https://github.com/Zhaph/middleearth-sbg/tree/MiddleEarth), mostly so that I can re-use a lot of the rules etc, and I've been updating the .gst for starters (references, values, etc.) - I assume you would need to create the new repo within BSData and then I can apply to join it and start building up the work in there?

**Comment by cordwartman** [comment]
@Zhaph I was looking at taking a crack at working on the BS file for MESBG too if you would like the help!

**Comment by Zhaph** [comment]
Hi @cordwartman great to have some help, I'm about two thirds of the way through the "special rules" in the `middleearth` branch of my fork, but I should probably take the catalogue files out as I've probably broken them horribly while I pull out various old rules etc.

I plan of following the existing Hobbit structure fairly closely, with any rules shared between warbands in the root gst file, but anything warband specific in the appropriate catalogue.

**Comment by Zhaph** [comment]
I've created [a project and some issues](https://github.com/Zhaph/middleearth-sbg/projects/1) to get started.

**Comment by cordwartman** [comment]
My work sent me to a different office for the week because of the hurricane, I may have time this weekend to put in some work updating an army list, probably take a shot at Isengard.

**Comment by Zhaph** [comment]
No worries @cordwartman - feel free to take a stab at it. You'll see that I've moved the original `.cat` files into a folder called "original" until I start working on them - stops the Roster editor having a fit that they are broken when you open the game system.

**Comment by Zhaph** [comment]
@amis92 Just to let you know, we're getting there with port on my fork of The Hobbit, do you want to wait until we're "first pass" complete before you set up an "official" repo, or should we start considering the move sooner?

As I see it there are pros and cons to both:

1. We'll have more visibility, and therefore more potential help.
2. We've only got about 4 or 5 armies ready at the moment, but a lot of groundwork has now been completed.
3. We're still in a bit of flux (i.e. settling on how we manage models that appear in multiple lists, etc - roll on 2.2 I say) so anyone that starts using it may have breaking changes.
4. There are quite a few known issues around list validity.

**Comment by Zhaph** [comment]
Sounds great @amis92 much appreciated. Will happily hold off creating releases.

**Comment by Zhaph** [comment]
If you could also give @cordwartman write access, that would be great, we're working together on it nicely at the moment.

**Comment by Zhaph** [comment]
> Hi, I've been on vacation, so now that I'm back, we can create the repo. Which doesn't mean it needs to be released immediately. I'd say that first release should contain at least all armies/catalogues. Validation issues are of less concern.
> 
> So I'll go ahead and create the new repo, and give you write access - but I'd advise not to create a release until you're providing at least all armies and units, validation aside.

Any word on the new, empty repo yet @amis92 ?

**Comment by amis92** [comment]
Hi @Zhaph, @cordwartman,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully.
Also I created a new, org-linked Gitter chat room (GitHub login): [![Join the chat at Gitter][gitter-badge]][gitter].

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/middle-earth
[invitation]: https://github.com/BSData/middle-earth/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
[gitter-badge]: https://badges.gitter.im/Join%20Chat.svg
[gitter]: https://gitter.im/BSData/middle-earth?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by Zhaph** [comment]
Many thanks :)
