### ISSUE TITLE
New repo: Add new game to battlescribe - Space Wreckers

### ISSUE THREAD

**Issue by SpaceWreckers** [BSData/catalogue-development#231]
Hello.
I am the creator of a new skirmish game - Space Wreckers
I would love to make crew generation available on Battlescribe.

Although I'm not particularly techy I am more than happy to have a go at the inputting/onboarding process myself.

I have the rules in both Word and Excel and can transfer over to whatever system you use

Looking forward to hearing from you

Hector

**Comment by Mad-Spy** [comment]
Data sets are created by the community of the game; you will need to create the data yourself. 

See the wiki page on this repo for details of how to get set up. Given that your game is likely to have a relatively small user base, you should look at self-hosting the data via GitHub.
