### ISSUE TITLE
New repo: Warhammer Fantasy 6º Ampliada (español)

### ISSUE THREAD

**Issue by barondepretto** [BSData/catalogue-development#232]
Warhammer Fantasy 6º Ampliada, diciembre 2023
[battlescribe6A copia.zip](https://github.com/BSData/catalogue-development/files/13620642/battlescribe6A.copia.zip)

**Comment by Mad-Spy** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
