### ISSUE TITLE
Battlescribe app not seeing repositories

### ISSUE THREAD

**Issue by zvshrawder** [BSData/catalogue-development#233]
**Describe the bug**
So when I now log onto Battlescribe (latest version for both Windows and Android), I only see three games in the catalog (use to see WH10th 9th etc, Gaslands, Xenos Rampant). All I see are the 3 at the bottom of your group page  (https://battlescribedata.appspot.com/#/repos).

**To Reproduce**
Should just need to update battlescribe and look at the data tab.

**Expected behavior**
Only the before mentioned games show up under the data tab. But previously downloaded ones ar still chosable when creating or viewing a roster.

**Screenshots**
![image](https://github.com/BSData/catalogue-development/assets/49354626/828ee836-bd32-4c70-a996-ad2d948b9b7d)

**Device and data (please complete the following information):**
 - OS: Android/ Windows 10
 - App being used to create lists: Battlescribe
 - App version: v2.03.27.341/v2.03.21.166
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mad-Spy** [comment]
Fyi, this is not the support channel for Battlescribe. This is for support with creating data. Data authors are not affiliated with the Battlescribe app dev.

**Comment by hutber** [comment]
However the answer is here @zvshrawder 
https://github.com/BSData/gallery#battlescribe
