### ISSUE TITLE
New repo: Trench crusade

### ISSUE THREAD

**Issue by SoulsR** [BSData/catalogue-development#236]
Hello, I just joined the discord and was looking for a way to create a repository in order to write data for the skirmish game Trench Crusade which is currently in developpment and playtest. here is the link to their website : https://www.trenchcrusade.com/

I, and all the people invested in the project, be it the players or the game creators, would be very grateful if we could use BSData for the game.

Cordially.

**Comment by Mad-Spy** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
