### ISSUE TITLE
New repo: new game system

### ISSUE THREAD

**Issue by jon3man** [BSData/catalogue-development#237]
I'm nearing the beta testing stages of a miniatures agnostic game system.  I figure that having the data sheets for this game in battlescribe would enable more people to easily help with testing (far easier than dealing with printing Google docs sheets).

While the game system has a lot of new goodness to bring to the table, this is my first venture into designing in the war games space. As such, any and all assistance would be greatly appreciated.

Likewise, if you have any questions regarding the game, i would be more than happy to answer them.

**Comment by Mad-Spy** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories
