### ISSUE TITLE
New repo: Wild West Exodus 3.04c

### ISSUE THREAD

**Issue by ChainlightningO** [BSData/catalogue-development#240]
Hi, I would like to start a new repository for the game Wild West Exodus (Third Edition). There is another repository for Second edition (2.1.4) and hasn´t been updated since 2019.

Regards,

Mauricio Yap

**Comment by OftKilted** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

**Comment by amis92** [comment]
Hi, I've added you as a Maintainer to that repository. Feel free to remove all existing files if you expect noone to use these old files/plays 2nd ed. Put your files in there. Read through the linked docs, don't hesitate to chat on discord. Welcome! https://github.com/BSData/Wild-West-Exodus/invitations

**Comment by ChainlightningO** [comment]
Thanks, I´ve cloned the repository and I´m modifying the data on
Battlescribe Data Editor.

**Comment by Mad-Spy** [comment]
We would strongly recommend that you switch to using the New Recruit data editor instead so that you can receive support for any issues you encounter. Battlescribe has been abandoned by its developer.

https://github.com/giloushaker/nr-editor/releases

**Comment by ChainlightningO** [comment]
Thanks, I'll check it out.
