### ISSUE TITLE
New repo: warhammer 40k in spanish

### ISSUE THREAD

**Issue by eugwyn** [BSData/catalogue-development#241]
hello.
I have been translating the chaos index and the basic instructions for Warhammer 40k into Spanish for some time with success. Now I'm starting with the imperial knights index.
I would like to be able to upload these translated caodex with you so that everyone can enjoy this hobby in Spanish.
I can send you a proof of your translated data so you can see that I am serious.
I hope it can be accepted in your community and thank you for your time.
I hope your answer.
thank you

**Comment by OftKilted** [comment]
Please see the link below for details of how to host the repo in your personal org and share it with others.

https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories

**Comment by amis92** [comment]
Sorry to disappoint you, but an extensive discussion and resolution about translations is here: https://github.com/BSData/catalogue-development/issues/15
