### ISSUE TITLE
New Repo: Warzone Eternal

### ISSUE THREAD

**Issue by SpecialAgent45954** [BSData/catalogue-development#242]
Hello, I am in contact and in agreement with Res Nova, who is the publisher of the new edition of Mutant Chronicles Warzone, whose name will be Warzone Eternal, and I would like to request the creation of the Repository for this new game.

Thanks

**Comment by Mad-Spy** [comment]
As per the comment on Discord, please follow the instructions at https://github.com/BSData/catalogue-development/wiki/Help:-Hosting-repositories to host your repo in Github.
