### ISSUE TITLE
New Repo: Age of Sigmar 4th

### ISSUE THREAD

**Issue by exaegrum** [BSData/catalogue-development#243]
I'm creating the datafiles for Age of Sigmar 4th ed, and want the repository set up under the BSData org. Could this be initialized and myself added to it?

**Comment by exaegrum** [comment]
no changes necessary

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/9940531297)
