### ISSUE TITLE
New repo: Adeptus Titanicus 2018

### ISSUE THREAD

**Issue by the-koetjeboe** [BSData/catalogue-development#244]
name: at-2018
As discussed on discord [here](https://discord.com/channels/558412685981777922/741281191868760284/1260902319546044458) we would like to 'deprecated' the current Adeptus Titanicus repo to leave it in a BS compatible state without disturbing the current users. We then would like a new repo in which we can continue development that takes advantage of the new features available in NR, my suggestion would be repository name 'at-2018' and description 'Adeptus Titanicus 2018'

I'm not sure how we best move over contributors (they might not be interested I suppose), we could have people re-request access but at least the following contributors contributed in the past year (besides me):

@TrentBartlem (admin of the old repo)
@zopha
@nygellyndley

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/9907338913)
