### ISSUE TITLE
New repo: Dropfleet Commander (2024)

### ISSUE THREAD

**Issue by Kemp-J** [BSData/catalogue-development#247]
name: dropfleet-commander-2024

The Dropfleet Commander data is in BSData/dropfleet-commander, for which I am a maintainer. With the second edition soon to be released it would be good to have a repo for that edition as well.

**Comment by Mad-Spy** [comment]
/approve
[Workflow run](https://github.com/BSData/catalogue-development/actions/runs/11241035681)
