### ISSUE TITLE
New repo: Hail Caesar

### ISSUE THREAD

**Issue by EmperorMeer** [BSData/catalogue-development#25]
Hello,

I am a fan of the game Hail Caesar and while there are a few Warlord Games games on Battlescibe there is not yet one for Hail Caesar.

**Comment by amis92** [comment]
Hi @EmperorMeer,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to that repo
3. You accept the invitation and gain push/write access to that new repo
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

PS that also means you'll need to create these data files.

**Comment by amis92** [comment]
Almost two months no answer, closing as timed out.
