### ISSUE TITLE
New repo: Monsterpocalypse

### ISSUE THREAD

**Issue by xerusjoe** [BSData/catalogue-development#27]
Since this game is coming back, I'd like to make a repository for this. The entries are fairly basic, and I have already made an extremely simple version just to have something for the time being.

**Comment by xerusjoe** [comment]
Would you like me to put the 3 files I have in here for the time being? I'm not sure if I should be waiting for anything for making a new repository.

**Comment by amis92** [comment]
Hi, sorry, the issue got lost in my task list. Are you still here? Can you create your own repository with the files for now at least, so I can take a loot at your files? :)

**Comment by xerusjoe** [comment]
I don't know how to make a repository on here, but here are the files.

[Monsterpocalypse.zip](https://github.com/BSData/catalogue-development/files/2622974/Monsterpocalypse.zip)

**Comment by xerusjoe** [comment]
Also, I think I figured it out. This?
https://github.com/xerusjoe/Monsterpocalypse

**Comment by amis92** [comment]
Perfect!

**Comment by amis92** [comment]
Hi @xerusjoe,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at Gitter][gitter-badge]][gitter] - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/monsterpocalypse
[invitation]: https://github.com/BSData/monsterpocalypse/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
[gitter-badge]: https://badges.gitter.im/Join%20Chat.svg
[gitter]: https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
