### ISSUE TITLE
Mechanicum Tahgmata

### ISSUE THREAD

**Issue by Molecule4** [BSData/catalogue-development#28]
This is a polite request for someone to do a data folder for this fan-dex: [https://img.fireden.net/tg/image/1518/48/1518481249843.pdf](url)

It's someones homebrew of what the Mechanicum Tahgmata could look like in 8th edition. This is completely selfish of me to ask, so I'd understand if it was turned down. To anyone who would be kind enough to do it though, I thank you. Sorry if this wastes anyones time, and keep up the good work. It's always appreciated.

**Comment by capitaladot** [comment]
DIY.
