### ISSUE TITLE
How To: Unit leader upgrades

### ISSUE THREAD

**Issue by amis92** [BSData/catalogue-development#3]
So the discussion is taken from [wh40k/#215](https://github.com/BSData/wh40k/issues/215#issuecomment-53170014). Let me quote:

@Kangodo wrote:

> [...] The problem is that both the unit AND the Exarch-upgrade are options in the Entry Group.
> It looks like this, with the min/max behind it.
> Main Entry
> 
> > Entry Group: 0/infinite
> > 
> > > Models of 20 points: 5/10
> > > Upgrade of 10 points: 0/1
> > > The Main Entry asks the Entry Group what the minimum is, and the Entry Group says it's 0.
> > > So the Main Entry tells you that the minimum amount of points is 0.
> 
> An 'easy fix' would be to set the Entry Group at a min/max of 5 to 11 with a Default of the Models.
> Min = 5 because you need at least 5 models.
> Max = 11 because you can have a max of 10 models and the upgrade.
> That would mean the Entry Group now replies with "I need at least 5 selections and my Default are the models, so that's 100 points." and the Main Entry would reflect this.
> 
> Someone that knows the Codex could probably do that in 15 minutes. If I were to do it, it would take hours because I had to look everything up in a PDF ;) Just to make sure I didn't make any mistakes.

@amis92 wrote:

> While I'm here, I'll put forth an academic discussion.
> 
> (mind you it's not directed at anybody; rather a proposition)
> I'm decidedly against such Grouping. I imagine a Group being a choice of similarly-weighted Entries. What I cannot stand are such Groups as mentioned above, where in single Group we buy both _models_ and _upgrades_ to them.
> 
> I'd see it two ways: _either_ knock Exarch upgrade out of the group _or_ turn upgrade Entry into Exarch entry, which would have the cost of model and upgrade, and represent an actual Exarch.
> 
> I prefer making such choices as they seem to look like: make a Group of _models_ available in unit and set limits appropriately. Exarch is a model, not an upgrade in this scenario.
> 
> All this applies to units where leaders are optional upgrades.
> 
> Actually I think it should make it's way into catalogue-development.

Your thoughts?

**Comment by DrTobogganMD** [comment]
This topic is currently outdated with the various upgrades to Battlescribe in the last 6 years.
