### ISSUE TITLE
How To - Let selection entries update profile stats ?

### ISSUE THREAD

**Issue by BitPsycho** [BSData/catalogue-development#38]
For the game 'Vanguard' we have a number of 'common and rare items' that can be taken by ANY model within the roster so I defined 2 shared selection groups which are then assigned to each model.

Some of those items can influence the stats of a unit - eg ' a rare mount' would increase the speed of the model with 2.

I have a profile type 'warband member' which includes those stats and which are assigned to each model.

I would have hoped that I could have added a modifier to the 'items' which would allow me to update the profile but this does not seem possible ?

I did some further checks and I could only achieve this it seems by adding a modifier to the actual model - at that point I can access the profile type type ...  But even then I am not allowed to 'increment' the stat as it is not considered to be a number ( all stats seem string ).

Obviously adding the modifier directly to the model is very very cumbersome as I would have to add it to ALL members in ALL warbands for EVERY item that potentially could be selected ...

Am I missing something ?  Is there a way to achieve this within the current system ?

Thanks

**Comment by amis92** [comment]
I'd say that including screens would be really helpful. Images are worth 1000 words etc.

From what I gather, you should add the modifier to the shared profile, be it in an entry group or elsewhere.

If the stat you're trying to modify (select the field/stat/column first) is purely numeric, BattleScribe will allow you to choose Increment/Decrement as operation. Remember, select the field first, then the mode will show up.

**Comment by amis92** [comment]
@BitPsycho after re-reading the question, I think I might understand the issue: modifiers can only ever modify their direct parent. This means that if you want to modify a profile, you'll need to add the modifier to the profile, for each item that it can be affected by.

**Comment by BitPsycho** [comment]
@amis92 

You are right ... "pictures can tell a 1000 words" ..  I think you understood what I meant but just for the sake of clarification ..

Basically I want the below:

![2019-01-14_144259](https://user-images.githubusercontent.com/34598682/51116296-0048f900-180b-11e9-9584-6f2b04bcb777.jpg)

but then automatically whenever the user adds a rare item for any member of the roster ...

So ideally it would be nice to add a modifier directly on the item itself 

![2019-01-14_143855](https://user-images.githubusercontent.com/34598682/51116363-3ab29600-180b-11e9-8347-7100216e32af.jpg)

or on the profile type

![2019-01-14_143806](https://user-images.githubusercontent.com/34598682/51116386-456d2b00-180b-11e9-8e72-d32383430993.jpg)

but it does not seem to work like that ... for the reasons you stated ...

Obviously it does not make sense to copy the first screen entry for EVERY model in all warbands ...

**Comment by amis92** [comment]
Yeah, so what you want is indeed not easily achievable - adding modifiers to profile types would probably make the most sense, but it's essentially a feature request as it isn't possible currently. :)

**Comment by BitPsycho** [comment]
@amis92 ok understood ... should I log a new feature request or can you just add a label ? So this is ready next week ? :P

**Comment by amis92** [comment]
Feature requests: https://github.com/BattleScribe/Release/issues - extrapolating from current responsiveness of Jon (the developer of BattleScribe), you can hope for implementation in around 2021. ;)
