### ISSUE TITLE
How To: Unit upgrades (like special weapons)

### ISSUE THREAD

**Issue by amis92** [BSData/catalogue-development#4]
@Kangodo wrote

> Tactical Marines Squad
> 
> > Entry Group Marines 5/10
> > 
> > > Entry: Tactical Marine 4/9
> > > Entry Group 1/1 Sergeant
> > > 
> > > > Sergeant 0/1 (default)
> > > > Veteran Sergeant 0/1
> > 
> > Heavy Weapon with a min/max-modifier that looks to the amount of selections in 'Entry Group Marines'
> 
> That last line brings me to another question from https://github.com/BSData/wh40k/issues/261 which is kind of related:
> How do you prefer to do upgrades, on model or on unit-level?
> On model-level is 'more correct', but in my experience it's really slow and annoying to add the things you want since you have to select every model and its weapons. It also causes the roster-view to be extra long.
> On a unit-level means the model might not correctly replace it's old weapon, but it's much faster to create lists.

@senpai514 wrote:

> Some would be fine one way on unit level but others would be better model level depending on how many models can take upgrade much like the difference between an assault squad and then vanguard vet squad.

@Kangodo wrote:

> See Grey Knights (2014) for reference.
> Strike Squad: As I did it before: Weapons on unit-level. Not 100% correct, but clear and easy.
> Purgation Squad: Still on unit-level, but improved since I could make 8 entries. I do dislike the wordy options, makes it quite confusing on my phone.
> Terminators: Weapons on unit-level, cannot make each entry because there are 20 combinations.
> Paladins: Upgrades on model-level because there are too many combinations that are too important to create on unit-level.
> 
> So which of these units do you prefer?

**Comment by DrTobogganMD** [comment]
This topic is currently outdated with the various upgrades to Battlescribe in the last 6 years.
