### ISSUE TITLE
New repo: Warhammer: Age of Sigmar Skirmish

### ISSUE THREAD

**Issue by ghost** [BSData/catalogue-development#41]
Would be great to include Skirmish since the rules are getting updated in 2019. Should be able to use the points from existing AOS repo and converting. All units applicable but only 4 'factions' as they are Grand Alliance based.

**Comment by cartag** [comment]
Trying to convert this down to only 4 files will be impossible with all the rules currently in them. If it was done as list building only, with filters to show/hide units, it may be possible. I would like to see it as I'm a fan of Skirmish, but done in that sense may not be possible.

**Comment by enterdragon91** [comment]
Similiar to the official app then? chose GA on creation then add by a filtered faction list, eg show me the khorne units to add to my GA Chaos warband?

Totally game to help out on this but pretty limited to coding so I'd need a good bit of hand holding to start me off.

**Comment by EAndresen** [comment]
I would very much like this as well.
Is there some way to contribute to this, im new to AoS ande we are thinking of starting with Skirmish, now that Warcry aint what we were hoping for.

But there is a warscroll builder on there comunity site, but it is not giving all the ability and details we need for gaming.

**Comment by amis92** [comment]
So, hands up who's interested in actually building up the new repository had I created one?

**Comment by amis92** [comment]
Not much interest. Closing as stale.
