### ISSUE TITLE
New repo: Warlords of Erehwon

### ISSUE THREAD

**Issue by the3dwargamer** [BSData/catalogue-development#42]
I have been creating the data files for Warlord Games new game: Warlords of Erehwon.  I would like to get this listed under the BSData repo so the public will have it display on their list as available  I have created my own repository and have the current version of the files hosted there.  
https://github.com/the3dwargamer/WoEDatafiles

I am brand new to github and BS data creation.  I am about 75-80% done with the data files.  The catalogues finished are functional right now but there are just a few more factions I need to create still.  Also some fixes/upgrades to perform on the existing files.  

What further would I need to do so I can be shared on BSDATA? (besides actually finished the data files completely, estimate they will be completely done in 1 to 2 weeks)

**Comment by amis92** [comment]
Hi @the3dwargamer,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So  you'll have to do some work to make our website host those files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at Gitter][gitter-badge]][gitter] - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/warlords-of-erehwon
[invitation]: https://github.com/BSData/warlords-of-erehwon/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
[gitter-badge]: https://badges.gitter.im/Join%20Chat.svg
[gitter]: https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
