### ISSUE TITLE
New Repo: Rumbleslam

### ISSUE THREAD

**Issue by Kuinasan** [BSData/catalogue-development#47]
Hi i wrote the data for Rumbleslam and i like to upload it

**Comment by amis92** [comment]
Hi @Kuinasan,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/rumbleslam
[invitation]: https://github.com/BSData/rumbleslam/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
