### ISSUE TITLE
Roster Cost Limit

### ISSUE THREAD

**Issue by BitPsycho** [BSData/catalogue-development#49]
I have a couple of questions regarding cost limits.

I noticed that some users do not understand this field and sometimes just leave the field with its default value of '-1'.  This leads to issues in roster validations as some of my rules are based on the cost limit ( eg for each 40 pts of the roster do X or Y ).

Questions:

- Is it possible to enforce the input of a cost limit ?  Ideally even based upon the chosen force organization entry.

- Can a constraint / rule check be defined on the cost limit ?  I tried but couldn't really find something ... One can add a check on the current points of the roster but that is not the same as once a couple of units are chosen then the rule validates - even with  a cost limit of -1  => the 2 are not related.  Ideally again I would like to put these rules per force organization type.

**Comment by amis92** [comment]
As a quick answer, no these kind of things aren't currently possible. They're pretty good candidates for feature requests though. I'd suggest them on https://github.com/BattleScribe/Release - sometimes these suggestions get caught up by app developer and we gain new features. :)

**Comment by XWingDrLucky** [comment]
Similarly, ages ago I requested being able to set the default point value
in a game system file. I do a lot of games where the point values are
highly standardized, so being able to have new rosters default to that
value (rather than -1) would save trouble for most users (and users who
wanted something different could still change it).

**Comment by BitPsycho** [comment]
Added as new request https://github.com/BattleScribe/Release#59

**Comment by amis92** [comment]
Then I'll close this issue :)
