### ISSUE TITLE
Unofficial sources/fanmade stuff

### ISSUE THREAD

**Issue by Kangodo** [BSData/catalogue-development#5]
First of all, we now have 500 commits. Congratulations!

As to my question:
Lately I've been reading a lot of the Angry Marines and I was wondering how people would feel about it if I added a file for them?

For people who don't know what I am talking about:
Angry Marines are a /tg/ _slash_ fanmade Codex that is really popular, not just to play but they are really famous on the internet.
The fanmade-Codex can be found here: http://1d4chan.org/wiki/Codex_-_Angry_Marines
I think it would be a good idea because:
1) There are quite some people who play it.
2) People will love us for adding them.
3) Because Angry Marines.

Question two: If I have permission to add them, to what level should I censor the gigantic amount of swearing in their Codex? Or should I include a 'not for children'-tag to their name?

**Temper Maximus!**

**Comment by Crudercjm** [comment]
New repo: Mobile Suit Gundam Skirmish 

really fun game great fallowing

**Comment by amis92** [comment]
This topic is now closed in favour of #86. Please follow that issue for further announcements.
