### ISSUE TITLE
New repo: Punkapocalyptic

### ISSUE THREAD

**Issue by Drakice84** [BSData/catalogue-development#52]
Hello.
We wanted to add a new Game system called Punkapocalyptic.
Thankyou!

**Comment by Drakice84** [comment]
Hello!
Just for asking how this issue is going, we have all the files prepared to upload.
Thanks in advance!

**Comment by amis92** [comment]
Hi @Drakice84,

Please accept the invitation (admin level) in the email or on the [webpage][invitation]. Welcome aboard!

Here is the [repo][] you requested.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/punkapocalyptic
[invitation]: https://github.com/BSData/punkapocalyptic/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by Drakice84** [comment]
Thankyou very much!!
