### ISSUE TITLE
New repo: Blood Red Skies

### ISSUE THREAD

**Issue by Swamprat033** [BSData/catalogue-development#53]
Hi all, ive created a new game system for Blood Red Skies. Can you please create a Repo for this. Cheers
Tim

**Comment by amis92** [comment]
Hi @Swamprat033,

Please accept the invitation (admin level) in the email or on the [webpage][invitation]. Welcome aboard!

Here is the [repo][] you requested.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/blood-red-skies
[invitation]: https://github.com/BSData/blood-red-skies/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
