### ISSUE TITLE
New repo: Rogue Trader Adventures 

### ISSUE THREAD

**Issue by Ottodestruct** [BSData/catalogue-development#54]
I want to combine a few existing game systems to go back to a game that feels like old school rogue trader. , I would like to expand on some of the kill team rules and add a more robust experience system and some additional stats .

**Comment by amis92** [comment]
Generally I'll refer you to https://github.com/BSData/catalogue-development/issues/5

So quick answer is: most probably we won't host those.

We've made two exceptions: Heralds of Ruin Kill Team for 40k and 9th Age for Whfb. Both had a considerable amount of effort presented and people maintaining project.

Remember also, that you can always host datafiles on your own. Our site is a selection of what our community comes up with and we try to stick with commercial products or massively community-backed ones.

**Comment by Ottodestruct** [comment]
So where can I find a tutorial on making my own files?

**Comment by amis92** [comment]
You can browse our wiki here: https://github.com/BSData/catalogue-development/wiki

I'll also suggest that in general reverse engineering is the most common way people learn this stuff :)
