### ISSUE TITLE
New - Repo: Bolt Action 2.0

### ISSUE THREAD

**Issue by Toreador13** [BSData/catalogue-development#56]
Could you create a new Repo for Bolt Action 2.0? I would like to archive or retire the old Bolt Action files and start afresh with this as the new standard. Hopefully these files will be easier to maintain.

**Comment by OftKilted** [comment]
Is Bolt Action 2.0 a new game edition?

**Comment by Toreador13** [comment]
Yes, it follows the Bolt Action 2.0 rules set, which was minor changes and a new book. I revamped all the the data files to update it to take advantage of newer battlescribe functionality, so it's all from scratch. I am uncertain if anyone still uses the 1.0 files.

**Comment by XWingDrLucky** [comment]
For X-Wing Second Edition, I just added a new GST and CAT files for 2.0 in
the same repository as the first edition stuff. That way, anyone who
downloads gets both, the 1.0 rules are preserved, and 2.0 is available for
anyone who upgraded. Would that work here?

**Comment by Toreador13** [comment]
That may, Though I may need to rename some files. I will take a look and see.

**Comment by amis92** [comment]
It's also possible to just do a release before completely erasing all old files and pushing only new ones, packaging the old files into a .bsr that would be attached to the last 1.0 release and linking to it from README. See wh40k.

Keeping old files for no reason isn't really useful. Those select few who want can get them via link.

**Comment by amis92** [comment]
Also, I'll refrain from creating new repositories from new editions, unless there are some spectacularly special circumstances.
