### ISSUE TITLE
New repo: Zone Raiders

### ISSUE THREAD

**Issue by efalsken** [BSData/catalogue-development#60]
I’ve got the base system files just about done for Zone Raiders miniature skirmish game.

**Comment by efalsken** [comment]
You guys still use Gitter.im? Or is it a discord or Slack now? Can I get an invite?

**Comment by efalsken** [comment]
![image](https://user-images.githubusercontent.com/253640/60747810-f774ec80-9f3c-11e9-898e-bf8bbec576cb.png)

**Comment by amis92** [comment]
Repo created: https://github.com/BSData/zone-raiders
