### ISSUE TITLE
Bug: Warhammer 40K : Kill Team repository is no longer listed

### ISSUE THREAD

**Issue by Drogzar** [BSData/catalogue-development#61]
As per the title, the Kill Team repo https://github.com/BSData/wh40k-killteam is no longer listed in http://battlescribedata.appspot.com/#/repos so new users of Battlescribe can't get the date and existing users can't update it.

Sorry if this is not the right place to report it but I really couldn't find any other place.

**Comment by Drogzar** [comment]
It is listed again now.

**Comment by amis92** [comment]
See https://github.com/BSData/bsdata/issues/208
