### ISSUE TITLE
New repo: Ragnarok

### ISSUE THREAD

**Issue by apoapsis138** [BSData/catalogue-development#62]
I'd like to start developing a repo for Osprey's Ragnarok game

**Comment by amis92** [comment]
Hi @apoapsis138,

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system: [repo][]
2. I invite you to our organization
3. You accept the [invitation][] and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files.

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)


Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/ragnarok
[invitation]: https://github.com/BSData/ragnarok/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
