### ISSUE TITLE
New repo: Grimdark Future

### ISSUE THREAD

**Issue by sprutton1** [BSData/catalogue-development#68]
Any interest in hosting files for [Grimdark Future](https://onepagerules.com/portfolio/grimdark-future/)? I am willing to start creating/maintaining the ruleset.

**Comment by amis92** [comment]
@sprutton1 I have to say, we're on the fence here. We try to stick with the official/commercial projects, and avoid fanmade alternate rulesets. This qualifies as both. We've made exceptions in the past. For now I'll put this request on hold, ok?

**Comment by sprutton1** [comment]
Fine by me. I'm hosting it in my personal repo for now, but would prefer to have it be a part of the official set. I look forward to your decision.  Thanks

**Comment by amis92** [comment]
I've decided to not include this repository in our organization. You can follow #86 for notifications on an effort to allow any third-party ruleset to be hosted with BSData indexing.
