### ISSUE TITLE
New repo: Warhammer Fantasy Battle 7th Edition

### ISSUE THREAD

**Issue by DurzoBlintDeluxe** [BSData/catalogue-development#72]
Hi everyone. 
I couldn't find any repo for warhammer fantasy 7th Edition. Some guys out there still playing this version of the game.

**Comment by cartag** [comment]
Are you wanting to create the data files for it?

**Comment by DurzoBlintDeluxe** [comment]
Yep. I already started with a catalog.

**Comment by OftKilted** [comment]
There is currently a “Warhammer Fantasy” repository that covers WHFB.

You can request to join that group and submit files for the 7e version.
