### ISSUE TITLE
New/updated repo: Mordheim

### ISSUE THREAD

**Issue by fryiee** [BSData/catalogue-development#74]
The current BSData/mordheim repository has been archived as mordheim is obviously unsupported by GW now: https://github.com/BSData/mordheim

However, there's quite a large amount of people that still play and use a variety of rule sources for different warbands. This includes the rulebook and expansion warbands, as well as magazine releases. The majority of these warbands aren't present or up to date on the latest version of the data files.

I'd like to throw my hat in the ring to develop/expand on the existing data file for Mordheim or replace it with a new data file which includes, at the minimum, the graded content in the 1a-1b range as specified below: http://broheim.net/warbands.html , with the potential to expand it to 1c content also.

**Comment by amis92** [comment]
I've unarchived the repository and invited you. Your contributions are welcome.
