### ISSUE TITLE
Aeronautica Imperialis

### ISSUE THREAD

**Issue by amis92** [BSData/catalogue-development#76]
GW published a new game with the said name.

Tagging @guy-markman

**Comment by Guy-Markman** [comment]
It’s almost ready to beta. But it still need some work on it.

**Comment by 1p0rsus** [comment]
I have done the datafiles for both squadrons, Ork and Imperials. and implemented All the scenarios in the force list.
But I am new to github... Where do I post the index file? Thanks.

**Comment by 1p0rsus** [comment]
ok zip files !
[index.zip](https://github.com/BSData/catalogue-development/files/3642465/index.zip)

**Comment by Mad-Spy** [comment]
Hi @1p0rsus, as per his comment, @Guy-Markman has also been working on this. Once the repo is created, I suggest we out both versions into branches (as we'll need the raw .cat files) and then take the best bits of both implementations.

**Comment by Mad-Spy** [comment]
From @Guy-Markman on #77:  Hi @amis92 , my version of the code is ready to deployment. Would you mind creating a repo so I would be able to deploy it?

**Comment by amis92** [comment]
Hi @Guy-Markman @1p0rsus,

I've invited you.

This is the new [repo].

Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!


Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

**Please read carefully**:
As this is a new repository, please read Data Author Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

[repo]: https://github.com/BSData/aeronautica-imperialis
[invitation]: https://github.com/BSData/aeronautica-imperialis/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
