### ISSUE TITLE
Unwanted uncommited changes

### ISSUE THREAD

**Issue by Kangodo** [BSData/catalogue-development#8]
For some reason my Github keeps adding Uncommited changes I did not make.
Usually it are only the Adepta Sororitas from 40k, but sometimes it includes a bunch of datafiles.

It then tells me that I made changes like this:
Old: `<description>If the Cerastus Knight-Acheron opts to make a Run move rather than firing a weapon in the Shooting phase, it may move 3D6&quot;.</description>`

New: `<description>If the Cerastus Knight-Acheron opts to make a Run move rather than firing a weapon in the Shooting phase, it may move 3D6".</description>`

It seems to do that with multiple `&quot;`->`"` and `&apos;`->`'`.
Any idea what causes this and how do I stop this? Because now I have to discard a lot of changes every time I want to commit a REAL change.

**Comment by amis92** [comment]
Long-time deprecated.
