### ISSUE TITLE
New Repo: Star Breach

### ISSUE THREAD

**Issue by andreanespeca** [BSData/catalogue-development#82]
https://www.starbreach.com/ as i will play this very soon I will very likely create a datafile to easy roster creation, so willing to share.
It's almost same world of wh40k but with complete different easier set of rules.

**Comment by amis92** [comment]
.preview

**Comment by amis92** [comment]
.preview

**Comment by amis92** [comment]
.preview

**Comment by amis92** [comment]
.preview

**Comment by andreanespeca** [comment]
The one i have ready to upload is carniverse, can you make that one first, thanks

**Comment by amis92** [comment]
That'll probably fall under the same group as #68

**Comment by andreanespeca** [comment]
They planning to sell the book on their website starting next week but it's ok let see how it goes with that. Thanks

**Comment by andreanespeca** [comment]
The author have now got an agreement with slow death games to sell the book and collaboration for the future 
https://slowdeathgames.bigcartel.com
I personally think that the game is now a bit more then just fan made, let me know your opinion

**Comment by andreanespeca** [comment]
@amis92

**Comment by amis92** [comment]
I've decided to not include this repository in our organization. You can follow #86 for notifications on an effort to allow any third-party ruleset to be hosted with BSData indexing.
