### ISSUE TITLE
New repo: Kings of War: 3rd Edition

### ISSUE THREAD

**Issue by Ekaznae** [BSData/catalogue-development#85]
Yo yo! Would massively prefer to start a new repo for this one, and I'm sure the BS users would appreciate it. Wasn't even a third done updating the .gst and it was a cluttered eyesore! 3rd Ed of it is done now, though.. and I need to get some sleep.

Thanks a bunch! @amis92

**Comment by amis92** [comment]
We're not creating new repositories for existing game's new editions.

You can delete all old datafiles and only have new ones, or keep both old and new with different game system ID.

If you have further questions, please ask.

**Comment by Ekaznae** [comment]
Apologies. I believe I can only include 1 game system file in a repository, though, yes? Or is that just an older limitation?

**Comment by amis92** [comment]
I don't think there was such a limitation at any point in time, but yes - you can include more than one game system per repository. You just need all of them to have unique/different IDs.

**Comment by Ekaznae** [comment]
That is great news! Thank you!
