### ISSUE TITLE
New Repo: Marvel Crisis Protocol

### ISSUE THREAD

**Issue by teage-like-league** [BSData/catalogue-development#88]
Repository Name: marvel-crisis-protocol
Repository Description: Battlescribe Data for Marvel: Crisis Protocol The Miniature Game
Collaborators To Invite: @teage-like-league

**Comment by jmatchett** [comment]
@teage-like-league can I be added as a collaborator as well?

**Comment by amis92** [comment]
@teage-like-league are you still interested? I don't know how, but I missed the notification about this issue...

@jmatchett if @teage-like-league agrees, sure I can add you.

**Comment by teage-like-league** [comment]
@amis92 yes please, I am still interested.
I am absolutely in favor of some help from @jmatchett

**Comment by amis92** [comment]
.approve
