### ISSUE TITLE
Not counting towards parent category

### ISSUE THREAD

**Issue by Cruentus-Tigris** [BSData/catalogue-development#9]
hello,

in the skaven cat there are two units in the core that dont count for points towards the allowance for core but points count for the army. is there a way to have them inside the core block but the points don't get included for core?

**Comment by amis92** [comment]
Nope. Such units are handled by being assigned to (no category) or to another not-limiting category. In 40k we've created "No Force Org Slot" category for units not counting towards allowance, be it point cost or selection count allowance.

**Comment by amis92** [comment]
Also, I've renamed, because this discussion repo is created to handle generic questions. For skaven-specific, please use whfb issues.

**Comment by amis92** [comment]
Deprecated by time.
