### ISSUE TITLE
How do I implement a cost constraint across two child forces?

### ISSUE THREAD

**Issue by coldgap** [BSData/catalogue-development#91]
I'm trying to model the rule "Well Supported" in Heavy Gear Blitz! (rules available at https://www.drivethrurpg.com/product/144759/Heavy-Gear-Blitz-Tabletop-Wargaming--Living-Rulebook?term=heavy+gear+blitz, specific rule on page 72), and I've gotten most of the way... but I'm having trouble constraining the number of actions across two units.

(I've got a repository at https://github.com/coldgap/Heavy-Gear-Blitz-LRB; the "Northern Guard" list has my current (incorrect) implementation of that function.)

In the rules that I'm working on, most rosters have multiple parent-level forces (Primary Units), each of which can have one child force (Support Units). Primary Units can have 4-6 Actions (I'm modelling Actions as a cost), and their accompanying Support Unit can have up to half-rounded-up as many Actions as were taken in the Primary Unit.
Some rosters--those with the rule "Well Supported"--may take two Support Units to each Primary Unit. However, the total number of Actions in those two Support Units must still conform to the half-rounded-up rule, e.g., Primary Unit with 5 Actions, Support Unit One with 2 Actions, and Support Unit Two with 1 Action.

If I implement the constraint on actions within the Support Unit, then it works correctly for normal rosters, but for "Well Supported" rosters each of the two Support Units could take that many actions. If I implement the constraint from the parent level, then the rule doesn't get applied at all.
 Any ideas?

**Comment by Mad-Spy** [comment]
@coldgap, did you manage to get this sorted with help on the Discord in the end?

**Comment by DrTobogganMD** [comment]
If you still have issues, please visit us on github.
