### ISSUE TITLE
New repo: Zone Alfa

### ISSUE THREAD

**Issue by RenMomo96** [BSData/catalogue-development#92]
Literally just came out today as of this posting and i really like the game. I have 0 experiance with this stuff, will more than likely fail hard and not get it right, and probably mess it up in more than 50 ways in 1 second, but i play with people online so pen and paper doesn't really cut it nowadays

**Comment by amis92** [comment]
Hi @RenMomo96 please read through #95 - it's a similar case here. :)

**Comment by Mad-Spy** [comment]
Have you got anywhere with creating these data files? If not, this request will be closed in 7 days.
