### ISSUE TITLE
New repo: Battlestar Galactica - Starship Battles 

### ISSUE THREAD

**Issue by Romanoaj31** [BSData/catalogue-development#95]
Hello,

Now that Aresgames has officially offered a scoring system for their Battlestar miniatures game ([https://www.aresgames.eu/25321](url)), I was curious about how to get a team builder started on here. Any advice would be helpful.

Kind regards,

Adam

**Comment by Romanoaj31** [comment]
.approve

**Comment by Romanoaj31** [comment]
.approve

**Comment by amis92** [comment]
>I was curious about how to get a team builder started on here.

So, are you interested in creating datafiles for this system? Or are you looking for people to do that? Because it's not clear for me.

**Comment by Romanoaj31** [comment]
I am new to Battlescribe. Was just seeing the feasibility of creating a Battlestar list-builder. Tabulating ships and attachments not convenient manually.  I would be helpful in creating datafiles / costs for various ships and upgrades.

**Comment by amis92** [comment]
You've not really answered my question.

**Comment by amis92** [comment]
Sorry if there's a confusion, the following is missing from wiki pages in regards to new repositories:

The organization is just an umbrella for various groups of people who create and maintain datafiles for the systems they play. So to have datafiles for a new system, you need to either create them yourself, or find people who will - we're all volunteers. If you want to do it yourself, we'll be more than happy to help you; however to get started it's best to reverse-engineer existing datafiles for a system you know already.

**Comment by Romanoaj31** [comment]
I'm interesting in creating datafiles.

**Comment by amis92** [comment]
Well then please read through the wiki https://github.com/BSData/catalogue-development/wiki try to reverse engineer, and when you have some datafiles ready, come back here. :) It'd be best if you set up your own repository and worked on the datafiles there, then when you have something we can discuss further.

Also, join the data author community over at discord! You can chat about datafiles with experienced authors.

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

**Comment by Romanoaj31** [comment]
Thanks. Will do.

**Comment by Mad-Spy** [comment]
Have you got anywhere with creating these data files? If not, this request will be closed in 7 days.
