### ISSUE TITLE
New repo: Judge Dredd Miniatures game-(WarlordGames)

### ISSUE THREAD

**Issue by Vescarea** [BSData/catalogue-development#96]
Hi, 
Could a new Repo be made for the newer Judge Dredd miniatures game as titled above? The other Judge Dredd repo is for the Mongoose games varient (older).

Thank you

**Comment by Vescarea** [comment]
.approve

**Comment by amis92** [comment]
Hi. In general, we don't create new repositories for new system editions. Is this a completely separate game system? Does it replace fully the old one, or are both supported?

**Comment by Vescarea** [comment]
yes its a completely new game system to the old one, just the old one was written by a different company and uses very different rules set. I guess i could just replace the current one with this new rules set.

**Comment by amis92** [comment]
The most important question is: is this new system replacing the old one, in terms of players? Are the models the same/compatible?

Or are these two completely disconnected from each other (say Age of Sigmar vs Warhammer Fantasy Battle).

But generally yeah, if it's a continuation of any kind - either put new files side-by-side (if there's an expectation of considerable amount of people still playing it), or just replace the old ones in their entirety. :)

**Comment by Vescarea** [comment]
yh I'll put the files side by side and see how it goes for now. People are still playing the old version and working on the files so i guess i could label them as "old" and "2019" versions to limit confusion.
