### ISSUE TITLE
New repo: Burrows & Badgers

### ISSUE THREAD

**Issue by Caranthar** [BSData/catalogue-development#97]
name: burrows-and-badgers
I'd like to add a catalogue for Burrows & Badgers.

**Comment by Caranthar** [comment]
.preview

**Comment by Caranthar** [comment]
.approve

**Comment by amis92** [comment]
@Caranthar thanks for the post! We're currently working on a new system of enlisting repositories with datafiles. Please start off by creating your own repository with the datafiles. We've got a nice template to start you up: https://github.com/BSData/TemplateDataRepo (click the green `Use this template` button).

For progress on enlisting external repositories, please follow #86

**Comment by Mad-Spy** [comment]
Have you got anywhere with creating these data files? If not, this request will be closed in 7 days.
